<?php

use Illuminate\Database\Seeder;

use Illuminate\Database\Eloquent\Model;
use App\Keyword;
use App\Topic;
use App\Chemtext;
use App\Problem;
use App\Solution;

class Chem5Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
$StartingMathematica = Topic::create(array('topic_name' => "Chem 5 - Starting Mathematica", 'video_url' => 'https://www.youtube.com/watch?start=1316&v=sAfZeueovi0', 'video_id' => "sAfZeueovi0", 'video_description' => ""));
$SimpleArithmeticOperations = Topic::create(array('topic_name' => "Chem 5 - Simple Arithmetic Operations", 'video_url' => 'https://www.youtube.com/watch?start=1387&v=sAfZeueovi0', 'video_id' => "sAfZeueovi0", 'video_description' => ""));
$CommonlyUsedNumbers = Topic::create(array('topic_name' => "Chem 5 - Commonly Used Numbers", 'video_url' => 'https://www.youtube.com/watch?start=2025&v=sAfZeueovi0', 'video_id' => "sAfZeueovi0", 'video_description' => ""));
$CommonMathematicalFunctions = Topic::create(array('topic_name' => "Chem 5 - Common Mathematical Functions", 'video_url' => 'https://www.youtube.com/watch?start=2229&v=sAfZeueovi0', 'video_id' => "sAfZeueovi0", 'video_description' => ""));
$PlottingFunctions = Topic::create(array('topic_name' => "Chem 5 - Plotting Functions", 'video_url' => 'https://www.youtube.com/watch?start=99&v=2SQMO9y7sfg', 'video_id' => "2SQMO9y7sfg", 'video_description' => ""));
$MathematicaHelpMenu = Topic::create(array('topic_name' => "Chem 5 - Mathematica Help Menu", 'video_url' => 'https://www.youtube.com/watch?start=651&v=2SQMO9y7sfg', 'video_id' => "2SQMO9y7sfg", 'video_description' => ""));
$ManipulatingaPlot = Topic::create(array('topic_name' => "Chem 5 - Manipulating a Plot", 'video_url' => 'https://www.youtube.com/watch?start=845&v=2SQMO9y7sfg', 'video_id' => "2SQMO9y7sfg", 'video_description' => ""));
$PlotLegends = Topic::create(array('topic_name' => "Chem 5 - Plot Legends", 'video_url' => 'https://www.youtube.com/watch?start=2235&v=2SQMO9y7sfg', 'video_id' => "2SQMO9y7sfg", 'video_description' => ""));
$AssigningVariables = Topic::create(array('topic_name' => "Chem 5 - Assigning Variables", 'video_url' => 'https://www.youtube.com/watch?start=2783&v=2SQMO9y7sfg', 'video_id' => "2SQMO9y7sfg", 'video_description' => ""));
$DefiningFunctions = Topic::create(array('topic_name' => "Chem 5 - Defining Functions", 'video_url' => 'https://www.youtube.com/watch?start=3223&v=2SQMO9y7sfg', 'video_id' => "2SQMO9y7sfg", 'video_description' => ""));
$Comments = Topic::create(array('topic_name' => "Chem 5 - Comments", 'video_url' => 'https://www.youtube.com/watch?start=4404&v=2SQMO9y7sfg', 'video_id' => "2SQMO9y7sfg", 'video_description' => ""));
$SymbolicUnits = Topic::create(array('topic_name' => "Chem 5 - Symbolic Units", 'video_url' => 'https://www.youtube.com/watch?start=108&v=aCf8EcCklrg', 'video_id' => "aCf8EcCklrg", 'video_description' => ""));
$UnitsforAverageEnergy = Topic::create(array('topic_name' => "Chem 5 - Units for Average Energy", 'video_url' => 'https://www.youtube.com/watch?start=624&v=aCf8EcCklrg', 'video_id' => "aCf8EcCklrg", 'video_description' => ""));
$PredefinedUnits = Topic::create(array('topic_name' => "Chem 5 - Predefined Units", 'video_url' => 'https://www.youtube.com/watch?start=703&v=aCf8EcCklrg', 'video_id' => "aCf8EcCklrg", 'video_description' => ""));
$ConvertCommand = Topic::create(array('topic_name' => "Chem 5 - Convert Command", 'video_url' => 'https://www.youtube.com/watch?start=986&v=aCf8EcCklrg', 'video_id' => "aCf8EcCklrg", 'video_description' => ""));
$Constants = Topic::create(array('topic_name' => "Chem 5 - Constants", 'video_url' => 'https://www.youtube.com/watch?start=1312&v=aCf8EcCklrg', 'video_id' => "aCf8EcCklrg", 'video_description' => ""));
$Palette = Topic::create(array('topic_name' => "Chem 5 - Palette", 'video_url' => 'https://www.youtube.com/watch?start=1656&v=aCf8EcCklrg', 'video_id' => "aCf8EcCklrg", 'video_description' => ""));
$ReplacementRules = Topic::create(array('topic_name' => "Chem 5 - Replacement Rules", 'video_url' => 'https://www.youtube.com/watch?start=3008&v=aCf8EcCklrg', 'video_id' => "aCf8EcCklrg", 'video_description' => ""));
$Legend = Topic::create(array('topic_name' => "Chem 5 - Legend", 'video_url' => 'https://www.youtube.com/watch?start=3474&v=aCf8EcCklrg', 'video_id' => "aCf8EcCklrg", 'video_description' => ""));
$ListsandTables = Topic::create(array('topic_name' => "Chem 5 - Lists and Tables", 'video_url' => 'https://www.youtube.com/watch?start=3742&v=aCf8EcCklrg', 'video_id' => "aCf8EcCklrg", 'video_description' => ""));
$ListManipulation = Topic::create(array('topic_name' => "Chem 5 - List Manipulation", 'video_url' => 'https://www.youtube.com/watch?start=23&v=0YkWqesUSOw', 'video_id' => "0YkWqesUSOw", 'video_description' => ""));
$DefiningaMatrix = Topic::create(array('topic_name' => "Chem 5 - Defining a Matrix", 'video_url' => 'https://www.youtube.com/watch?start=332&v=0YkWqesUSOw', 'video_id' => "0YkWqesUSOw", 'video_description' => ""));
$TransposeOperation = Topic::create(array('topic_name' => "Chem 5 - Transpose Operation", 'video_url' => 'https://www.youtube.com/watch?start=512&v=0YkWqesUSOw', 'video_id' => "0YkWqesUSOw", 'video_description' => ""));
$UsingaMatrixtofindRateLaw = Topic::create(array('topic_name' => "Chem 5 - Using a Matrix to find Rate Law", 'video_url' => 'https://www.youtube.com/watch?start=627&v=0YkWqesUSOw', 'video_id' => "0YkWqesUSOw", 'video_description' => ""));
$ListPlot = Topic::create(array('topic_name' => "Chem 5 - List Plot", 'video_url' => 'https://www.youtube.com/watch?start=969&v=0YkWqesUSOw', 'video_id' => "0YkWqesUSOw", 'video_description' => ""));
$IntegratedRateLaws = Topic::create(array('topic_name' => "Chem 5 - Integrated Rate Laws", 'video_url' => 'https://www.youtube.com/watch?start=1201&v=0YkWqesUSOw', 'video_id' => "0YkWqesUSOw", 'video_description' => ""));
$LeastSquareFitting = Topic::create(array('topic_name' => "Chem 5 - Least Square Fitting", 'video_url' => 'https://www.youtube.com/watch?start=1705&v=0YkWqesUSOw', 'video_id' => "0YkWqesUSOw", 'video_description' => ""));
$AddingaThirdTerm = Topic::create(array('topic_name' => "Chem 5 - Adding a Third Term", 'video_url' => 'https://www.youtube.com/watch?start=2441&v=0YkWqesUSOw', 'video_id' => "0YkWqesUSOw", 'video_description' => ""));
$ShowCommand = Topic::create(array('topic_name' => "Chem 5 - Show Command", 'video_url' => 'https://www.youtube.com/watch?start=2838&v=0YkWqesUSOw', 'video_id' => "0YkWqesUSOw", 'video_description' => ""));
$Polynomial = Topic::create(array('topic_name' => "Chem 5 - Polynomial", 'video_url' => 'https://www.youtube.com/watch?start=124&v=LnjorNxFZJ4', 'video_id' => "LnjorNxFZJ4", 'video_description' => ""));
$LeastSquaresFit = Topic::create(array('topic_name' => "Chem 5 - Least Squares Fit", 'video_url' => 'https://www.youtube.com/watch?start=262&v=LnjorNxFZJ4', 'video_id' => "LnjorNxFZJ4", 'video_description' => ""));
$EnergyProfile = Topic::create(array('topic_name' => "Chem 5 - Energy Profile", 'video_url' => 'https://www.youtube.com/watch?start=1869&v=LnjorNxFZJ4', 'video_id' => "LnjorNxFZJ4", 'video_description' => ""));
$MeanandVariance = Topic::create(array('topic_name' => "Chem 5 - Mean and Variance", 'video_url' => 'https://www.youtube.com/watch?start=2305&v=LnjorNxFZJ4', 'video_id' => "LnjorNxFZJ4", 'video_description' => ""));
$Histogram = Topic::create(array('topic_name' => "Chem 5 - Histogram", 'video_url' => 'https://www.youtube.com/watch?start=2948&v=LnjorNxFZJ4', 'video_id' => "LnjorNxFZJ4", 'video_description' => ""));
$Permeations = Topic::create(array('topic_name' => "Chem 5 - Permeations", 'video_url' => 'https://www.youtube.com/watch?start=3730&v=LnjorNxFZJ4', 'video_id' => "LnjorNxFZJ4", 'video_description' => ""));
$BinomialCommand = Topic::create(array('topic_name' => "Chem 5 - Binomial Command", 'video_url' => 'https://www.youtube.com/watch?start=4476&v=LnjorNxFZJ4', 'video_id' => "LnjorNxFZJ4", 'video_description' => ""));
$BinomialCoefficient = Topic::create(array('topic_name' => "Chem 5 - Binomial Coefficient", 'video_url' => 'https://www.youtube.com/watch?start=20&v=v9BLyIgSPNA', 'video_id' => "v9BLyIgSPNA", 'video_description' => ""));
$ProbabilityofCoinFlip = Topic::create(array('topic_name' => "Chem 5 - Probability of Coin Flip", 'video_url' => 'https://www.youtube.com/watch?start=109&v=v9BLyIgSPNA', 'video_id' => "v9BLyIgSPNA", 'video_description' => ""));
$BinomialDistribution = Topic::create(array('topic_name' => "Chem 5 - Binomial Distribution", 'video_url' => 'https://www.youtube.com/watch?start=933&v=v9BLyIgSPNA', 'video_id' => "v9BLyIgSPNA", 'video_description' => ""));
$GaussianDistribution = Topic::create(array('topic_name' => "Chem 5 - Gaussian Distribution", 'video_url' => 'https://www.youtube.com/watch?start=1940&v=v9BLyIgSPNA', 'video_id' => "v9BLyIgSPNA", 'video_description' => ""));
$FunctionsofTwoVariables = Topic::create(array('topic_name' => "Chem 5 - Functions of Two Variables", 'video_url' => 'https://www.youtube.com/watch?start=4106&v=v9BLyIgSPNA', 'video_id' => "v9BLyIgSPNA", 'video_description' => ""));
$ThreeDPlot1 = Topic::create(array('topic_name' => "Chem 5 - 3D Plot", 'video_url' => 'https://www.youtube.com/watch?start=4522&v=v9BLyIgSPNA', 'video_id' => "v9BLyIgSPNA", 'video_description' => ""));
$MultivariableFunction = Topic::create(array('topic_name' => "Chem 5 - Multivariable Function", 'video_url' => 'https://www.youtube.com/watch?start=59&v=ka1-B09VIPI', 'video_id' => "ka1-B09VIPI", 'video_description' => ""));
$ThreeDPlot2 = Topic::create(array('topic_name' => "Chem 5 - 3D Plot", 'video_url' => 'https://www.youtube.com/watch?start=124&v=ka1-B09VIPI', 'video_id' => "ka1-B09VIPI", 'video_description' => ""));
$ChangingthePointofView = Topic::create(array('topic_name' => "Chem 5 - Changing the Point of View", 'video_url' => 'https://www.youtube.com/watch?start=1463&v=ka1-B09VIPI', 'video_id' => "ka1-B09VIPI", 'video_description' => ""));
$ContourPlot = Topic::create(array('topic_name' => "Chem 5 - Contour Plot", 'video_url' => 'https://www.youtube.com/watch?start=1721&v=ka1-B09VIPI', 'video_id' => "ka1-B09VIPI", 'video_description' => ""));
$LegendforContourPlot = Topic::create(array('topic_name' => "Chem 5 - Legend for Contour Plot", 'video_url' => 'https://www.youtube.com/watch?start=2123&v=ka1-B09VIPI', 'video_id' => "ka1-B09VIPI", 'video_description' => ""));
$ChangingContourStyle = Topic::create(array('topic_name' => "Chem 5 - Changing Contour Style", 'video_url' => 'https://www.youtube.com/watch?start=2854&v=ka1-B09VIPI', 'video_id' => "ka1-B09VIPI", 'video_description' => ""));
$PlottingFunctions = Topic::create(array('topic_name' => "Chem 5 - Plotting Functions", 'video_url' => 'https://www.youtube.com/watch?start=468&v=gNAski5fVuk', 'video_id' => "gNAski5fVuk", 'video_description' => ""));
$DrawingAtomicOrbitals = Topic::create(array('topic_name' => "Chem 5 - Drawing Atomic Orbitals", 'video_url' => 'https://www.youtube.com/watch?start=701&v=gNAski5fVuk', 'video_id' => "gNAski5fVuk", 'video_description' => ""));
$FunctionofThreeVariables = Topic::create(array('topic_name' => "Chem 5 - Function of Three Variables", 'video_url' => 'https://www.youtube.com/watch?start=989&v=gNAski5fVuk', 'video_id' => "gNAski5fVuk", 'video_description' => ""));
$TwopzOrbital = Topic::create(array('topic_name' => "Chem 5 - 2pz Orbital", 'video_url' => 'https://www.youtube.com/watch?start=1480&v=gNAski5fVuk', 'video_id' => "gNAski5fVuk", 'video_description' => ""));
$ThreeDzSquared = Topic::create(array('topic_name' => "Chem 5 - 3Dz Squared", 'video_url' => 'https://www.youtube.com/watch?start=1996&v=gNAski5fVuk', 'video_id' => "gNAski5fVuk", 'video_description' => ""));
$Derivative = Topic::create(array('topic_name' => "Chem 5 - Derivative", 'video_url' => 'https://www.youtube.com/watch?start=2676&v=gNAski5fVuk', 'video_id' => "gNAski5fVuk", 'video_description' => ""));
$PartialDerivative = Topic::create(array('topic_name' => "Chem 5 - Partial Derivative", 'video_url' => 'https://www.youtube.com/watch?start=3079&v=gNAski5fVuk', 'video_id' => "gNAski5fVuk", 'video_description' => ""));
$Momentum = Topic::create(array('topic_name' => "Chem 5 - Momentum", 'video_url' => 'https://www.youtube.com/watch?start=3618&v=gNAski5fVuk', 'video_id' => "gNAski5fVuk", 'video_description' => ""));
$ThermodynamicsExample = Topic::create(array('topic_name' => "Chem 5 - Thermodynamics Example", 'video_url' => 'https://www.youtube.com/watch?start=4069&v=gNAski5fVuk', 'video_id' => "gNAski5fVuk", 'video_description' => ""));
$ForceBetweenTwoAtoms = Topic::create(array('topic_name' => "Chem 5 - Force Between Two Atoms", 'video_url' => 'https://www.youtube.com/watch?start=49&v=tHJUPwYjpBA', 'video_id' => "tHJUPwYjpBA", 'video_description' => ""));
$Integration = Topic::create(array('topic_name' => "Chem 5 - Integration", 'video_url' => 'https://www.youtube.com/watch?start=1074&v=tHJUPwYjpBA', 'video_id' => "tHJUPwYjpBA", 'video_description' => ""));
$FresnelC = Topic::create(array('topic_name' => "Chem 5 - FresnelC", 'video_url' => 'https://www.youtube.com/watch?start=1470&v=tHJUPwYjpBA', 'video_id' => "tHJUPwYjpBA", 'video_description' => ""));
$ImproperIntegral = Topic::create(array('topic_name' => "Chem 5 - Improper Integral", 'video_url' => 'https://www.youtube.com/watch?start=1776&v=tHJUPwYjpBA', 'video_id' => "tHJUPwYjpBA", 'video_description' => ""));
$DummyVariables = Topic::create(array('topic_name' => "Chem 5 - Dummy Variables", 'video_url' => 'https://www.youtube.com/watch?start=2238&v=tHJUPwYjpBA', 'video_id' => "tHJUPwYjpBA", 'video_description' => ""));
$PlotsandIntegrals = Topic::create(array('topic_name' => "Chem 5 - Plots and Integrals", 'video_url' => 'https://www.youtube.com/watch?start=2447&v=tHJUPwYjpBA', 'video_id' => "tHJUPwYjpBA", 'video_description' => ""));
$PVWorkExample = Topic::create(array('topic_name' => "Chem 5 - PV Work Example", 'video_url' => 'https://www.youtube.com/watch?start=2567&v=tHJUPwYjpBA', 'video_id' => "tHJUPwYjpBA", 'video_description' => ""));
$Normalization = Topic::create(array('topic_name' => "Chem 5 - Normalization", 'video_url' => 'https://www.youtube.com/watch?start=3646&v=tHJUPwYjpBA', 'video_id' => "tHJUPwYjpBA", 'video_description' => ""));
$KineticTheoryofGasExample = Topic::create(array('topic_name' => "Chem 5 - Kinetic Theory of Gas Example", 'video_url' => 'https://www.youtube.com/watch?start=4285&v=tHJUPwYjpBA', 'video_id' => "tHJUPwYjpBA", 'video_description' => ""));
$RootMeanSquareSpeedExample = Topic::create(array('topic_name' => "Chem 5 - Root Mean Square Speed Example", 'video_url' => 'https://www.youtube.com/watch?start=22&v=vNovPD18plo', 'video_id' => "vNovPD18plo", 'video_description' => ""));
$EquationSolving = Topic::create(array('topic_name' => "Chem 5 - Equation Solving", 'video_url' => 'https://www.youtube.com/watch?start=1889&v=vNovPD18plo', 'video_id' => "vNovPD18plo", 'video_description' => ""));
$GeneralCubicEquationExample = Topic::create(array('topic_name' => "Chem 5 - General Cubic Equation Example", 'video_url' => 'https://www.youtube.com/watch?start=2365&v=vNovPD18plo', 'video_id' => "vNovPD18plo", 'video_description' => ""));
$GeneralCubicEquationExample = Topic::create(array('topic_name' => "Chem 5 - General Cubic Equation Example", 'video_url' => 'https://www.youtube.com/watch?start=63&v=T0upC6F9xUM', 'video_id' => "T0upC6F9xUM", 'video_description' => ""));
$QuinticPolynomial = Topic::create(array('topic_name' => "Chem 5 - Quintic Polynomial", 'video_url' => 'https://www.youtube.com/watch?start=277&v=T0upC6F9xUM', 'video_id' => "T0upC6F9xUM", 'video_description' => ""));
$GraphicalInterpretationofRoots = Topic::create(array('topic_name' => "Chem 5 - Graphical Interpretation of Roots", 'video_url' => 'https://www.youtube.com/watch?start=413&v=T0upC6F9xUM', 'video_id' => "T0upC6F9xUM", 'video_description' => ""));
$ComplexRoots = Topic::create(array('topic_name' => "Chem 5 - Complex Roots", 'video_url' => 'https://www.youtube.com/watch?start=726&v=T0upC6F9xUM', 'video_id' => "T0upC6F9xUM", 'video_description' => ""));
$DeterminingVariables = Topic::create(array('topic_name' => "Chem 5 - Determining Variables", 'video_url' => 'https://www.youtube.com/watch?start=1296&v=T0upC6F9xUM', 'video_id' => "T0upC6F9xUM", 'video_description' => ""));
$MassActionExample1 = Topic::create(array('topic_name' => "Chem 5 - Mass Action Example 1", 'video_url' => 'https://www.youtube.com/watch?start=1409&v=T0upC6F9xUM', 'video_id' => "T0upC6F9xUM", 'video_description' => ""));
$MassActionExampleofAcid = Topic::create(array('topic_name' => "Chem 5 - Mass Action Example of Acid", 'video_url' => 'https://www.youtube.com/watch?start=2366&v=T0upC6F9xUM', 'video_id' => "T0upC6F9xUM", 'video_description' => ""));
$CoupledEquilibrium = Topic::create(array('topic_name' => "Chem 5 - Coupled Equilibrium", 'video_url' => 'https://www.youtube.com/watch?start=3074&v=T0upC6F9xUM', 'video_id' => "T0upC6F9xUM", 'video_description' => ""));
$SodiumBicarbonateExample = Topic::create(array('topic_name' => "Chem 5 - Sodium Bicarbonate Example", 'video_url' => 'https://www.youtube.com/watch?start=88&v=vulG5ZqUDM0', 'video_id' => "vulG5ZqUDM0", 'video_description' => ""));
$IntroductiontoDifferentialEquation = Topic::create(array('topic_name' => "Chem 5 - Introduction to Differential Equation", 'video_url' => 'https://www.youtube.com/watch?start=1616&v=vulG5ZqUDM0', 'video_id' => "vulG5ZqUDM0", 'video_description' => ""));
$VerifyingaSolution = Topic::create(array('topic_name' => "Chem 5 - Verifying a Solution", 'video_url' => 'https://www.youtube.com/watch?start=2593&v=vulG5ZqUDM0', 'video_id' => "vulG5ZqUDM0", 'video_description' => ""));
$SolvingDifferentialEquationsExamples = Topic::create(array('topic_name' => "Chem 5 - Solving Differential Equations Examples", 'video_url' => 'https://www.youtube.com/watch?start=2821&v=vulG5ZqUDM0', 'video_id' => "vulG5ZqUDM0", 'video_description' => ""));
$HermiteH = Topic::create(array('topic_name' => "Chem 5 - HermiteH", 'video_url' => 'https://www.youtube.com/watch?start=3346&v=vulG5ZqUDM0', 'video_id' => "vulG5ZqUDM0", 'video_description' => ""));
$ExampleWithoutanExactAnswer = Topic::create(array('topic_name' => "Chem 5 - Example Without an Exact Answer", 'video_url' => 'https://www.youtube.com/watch?start=3434&v=vulG5ZqUDM0', 'video_id' => "vulG5ZqUDM0", 'video_description' => ""));
$InterpolatingFunction = Topic::create(array('topic_name' => "Chem 5 - Interpolating Function", 'video_url' => 'https://www.youtube.com/watch?start=3627&v=vulG5ZqUDM0', 'video_id' => "vulG5ZqUDM0", 'video_description' => ""));
$MultipleDifferentialEquations = Topic::create(array('topic_name' => "Chem 5 - Multiple Differential Equations", 'video_url' => 'https://www.youtube.com/watch?start=3821&v=vulG5ZqUDM0', 'video_id' => "vulG5ZqUDM0", 'video_description' => ""));
$ParametricPlot = Topic::create(array('topic_name' => "Chem 5 - Parametric Plot", 'video_url' => 'https://www.youtube.com/watch?start=4314&v=vulG5ZqUDM0', 'video_id' => "vulG5ZqUDM0", 'video_description' => ""));
$ChemicalKineticsProblems = Topic::create(array('topic_name' => "Chem 5 - Chemical Kinetics Problems", 'video_url' => 'https://www.youtube.com/watch?start=670&v=Yph20RSClwI', 'video_id' => "Yph20RSClwI", 'video_description' => ""));
$DefiningEquationsasaList = Topic::create(array('topic_name' => "Chem 5 - Defining Equations as a List", 'video_url' => 'https://www.youtube.com/watch?start=940&v=Yph20RSClwI', 'video_id' => "Yph20RSClwI", 'video_description' => ""));
$EquilibriumandChemicalKinetics = Topic::create(array('topic_name' => "Chem 5 - Equilibrium and Chemical Kinetics", 'video_url' => 'https://www.youtube.com/watch?start=1621&v=Yph20RSClwI', 'video_id' => "Yph20RSClwI", 'video_description' => ""));
$EquilibriumandChemicalKinetics = Topic::create(array('topic_name' => "Chem 5 - Equilibrium and Chemical Kinetics", 'video_url' => 'https://www.youtube.com/watch?start=129&v=ZAxwMRi6wmE', 'video_id' => "ZAxwMRi6wmE", 'video_description' => ""));
$TwoStepReaction = Topic::create(array('topic_name' => "Chem 5 - Two Step Reaction", 'video_url' => 'https://www.youtube.com/watch?start=992&v=ZAxwMRi6wmE', 'video_id' => "ZAxwMRi6wmE", 'video_description' => ""));
$DealingwithSeriesandSums = Topic::create(array('topic_name' => "Chem 5 - Dealing with Series and Sums", 'video_url' => 'https://www.youtube.com/watch?start=2082&v=ZAxwMRi6wmE', 'video_id' => "ZAxwMRi6wmE", 'video_description' => ""));
$TypesofWastoExpandFunctions = Topic::create(array('topic_name' => "Chem 5 - Types of Was to Expand Functions", 'video_url' => 'https://www.youtube.com/watch?start=2888&v=ZAxwMRi6wmE', 'video_id' => "ZAxwMRi6wmE", 'video_description' => ""));
$ExamplesofSeries = Topic::create(array('topic_name' => "Chem 5 - Examples of Series", 'video_url' => 'https://www.youtube.com/watch?start=3305&v=ZAxwMRi6wmE', 'video_id' => "ZAxwMRi6wmE", 'video_description' => ""));
$TrigonometricSeries = Topic::create(array('topic_name' => "Chem 5 - Trigonometric Series", 'video_url' => 'https://www.youtube.com/watch?start=3864&v=ZAxwMRi6wmE', 'video_id' => "ZAxwMRi6wmE", 'video_description' => ""));
$FourierSeries = Topic::create(array('topic_name' => "Chem 5 - Fourier Series", 'video_url' => 'https://www.youtube.com/watch?start=626&v=uXor4xkhmWw', 'video_id' => "uXor4xkhmWw", 'video_description' => ""));
$FourierTrigCommand = Topic::create(array('topic_name' => "Chem 5 - FourierTrig Command", 'video_url' => 'https://www.youtube.com/watch?start=1169&v=uXor4xkhmWw', 'video_id' => "uXor4xkhmWw", 'video_description' => ""));
$MathematicaDefaultInterval = Topic::create(array('topic_name' => "Chem 5 - Mathematica Default Interval", 'video_url' => 'https://www.youtube.com/watch?start=1749&v=uXor4xkhmWw', 'video_id' => "uXor4xkhmWw", 'video_description' => ""));
$SquareWave = Topic::create(array('topic_name' => "Chem 5 - Square Wave", 'video_url' => 'https://www.youtube.com/watch?start=2080&v=uXor4xkhmWw', 'video_id' => "uXor4xkhmWw", 'video_description' => ""));
$FormulastoSolveFourierTransforms = Topic::create(array('topic_name' => "Chem 5 - Formulas to Solve Fourier Transforms", 'video_url' => 'https://www.youtube.com/watch?start=84&v=Mlz2cNWKyz8', 'video_id' => "Mlz2cNWKyz8", 'video_description' => ""));
$TimeSignalanditsFourierTransform = Topic::create(array('topic_name' => "Chem 5 - Time Signal and its Fourier Transform", 'video_url' => 'https://www.youtube.com/watch?start=473&v=Mlz2cNWKyz8', 'video_id' => "Mlz2cNWKyz8", 'video_description' => ""));
$FourierAnalysisinMathematica = Topic::create(array('topic_name' => "Chem 5 - Fourier Analysis in Mathematica", 'video_url' => 'https://www.youtube.com/watch?start=652&v=Mlz2cNWKyz8', 'video_id' => "Mlz2cNWKyz8", 'video_description' => ""));
$SymbolicFourierTransforminMathematica = Topic::create(array('topic_name' => "Chem 5 - Symbolic Fourier Transform in Mathematica", 'video_url' => 'https://www.youtube.com/watch?start=1893&v=Mlz2cNWKyz8', 'video_id' => "Mlz2cNWKyz8", 'video_description' => ""));
$PartitionFunction = Topic::create(array('topic_name' => "Chem 5 - Partition Function", 'video_url' => 'https://www.youtube.com/watch?start=2501&v=Mlz2cNWKyz8', 'video_id' => "Mlz2cNWKyz8", 'video_description' => ""));
$SumCommand = Topic::create(array('topic_name' => "Chem 5 - Sum Command", 'video_url' => 'https://www.youtube.com/watch?start=3129&v=Mlz2cNWKyz8', 'video_id' => "Mlz2cNWKyz8", 'video_description' => ""));
$BoltzmannDistribution = Topic::create(array('topic_name' => "Chem 5 - Boltzmann Distribution", 'video_url' => 'https://www.youtube.com/watch?start=4179&v=Mlz2cNWKyz8', 'video_id' => "Mlz2cNWKyz8", 'video_description' => ""));
$TypesofDatabases = Topic::create(array('topic_name' => "Chem 5 - Types of Databases", 'video_url' => 'https://www.youtube.com/watch?start=125&v=obRrF6dS4ro', 'video_id' => "obRrF6dS4ro", 'video_description' => ""));
$ConnectingfromOffCampus = Topic::create(array('topic_name' => "Chem 5 - Connecting from Off-Campus", 'video_url' => 'https://www.youtube.com/watch?start=337&v=obRrF6dS4ro', 'video_id' => "obRrF6dS4ro", 'video_description' => ""));
$SciFinderScholarSFS = Topic::create(array('topic_name' => "Chem 5 - SciFinder Scholar (SFS)", 'video_url' => 'https://www.youtube.com/watch?start=395&v=obRrF6dS4ro', 'video_id' => "obRrF6dS4ro", 'video_description' => ""));
$LibrarysWebsite = Topic::create(array('topic_name' => "Chem 5 - Library's Website", 'video_url' => 'https://www.youtube.com/watch?start=441&v=obRrF6dS4ro', 'video_id' => "obRrF6dS4ro", 'video_description' => ""));
$SciFinderLoginandDatabase = Topic::create(array('topic_name' => "Chem 5 - SciFinder Login and Database", 'video_url' => 'https://www.youtube.com/watch?start=473&v=obRrF6dS4ro', 'video_id' => "obRrF6dS4ro", 'video_description' => ""));
$CitationDatabase = Topic::create(array('topic_name' => "Chem 5 - Citation Database", 'video_url' => 'https://www.youtube.com/watch?start=2278&v=obRrF6dS4ro', 'video_id' => "obRrF6dS4ro", 'video_description' => ""));
$WebofScience = Topic::create(array('topic_name' => "Chem 5 - Web of Science", 'video_url' => 'https://www.youtube.com/watch?start=2480&v=obRrF6dS4ro', 'video_id' => "obRrF6dS4ro", 'video_description' => ""));
$GoogleScholar = Topic::create(array('topic_name' => "Chem 5 - Google Scholar", 'video_url' => 'https://www.youtube.com/watch?start=2735&v=obRrF6dS4ro', 'video_id' => "obRrF6dS4ro", 'video_description' => ""));
$NumericalDatabase = Topic::create(array('topic_name' => "Chem 5 - Numerical Database", 'video_url' => 'https://www.youtube.com/watch?start=4055&v=obRrF6dS4ro', 'video_id' => "obRrF6dS4ro", 'video_description' => ""));
$Knovel = Topic::create(array('topic_name' => "Chem 5 - Knovel", 'video_url' => 'https://www.youtube.com/watch?start=4147&v=obRrF6dS4ro', 'video_id' => "obRrF6dS4ro", 'video_description' => ""));
$OtherNumericalDatabases = Topic::create(array('topic_name' => "Chem 5 - Other Numerical Databases", 'video_url' => 'https://www.youtube.com/watch?start=4520&v=obRrF6dS4ro', 'video_id' => "obRrF6dS4ro", 'video_description' => ""));
$RawNMRData = Topic::create(array('topic_name' => "Chem 5 - Raw NMR Data", 'video_url' => 'https://www.youtube.com/watch?start=35&v=1spoWKM2fZ0', 'video_id' => "1spoWKM2fZ0", 'video_description' => ""));
$DiscreteFourierTransform = Topic::create(array('topic_name' => "Chem 5 - Discrete Fourier Transform", 'video_url' => 'https://www.youtube.com/watch?start=265&v=1spoWKM2fZ0', 'video_id' => "1spoWKM2fZ0", 'video_description' => ""));
$PlottingDiscreteDataWithListPlot = Topic::create(array('topic_name' => "Chem 5 - Plotting Discrete Data With List Plot", 'video_url' => 'https://www.youtube.com/watch?start=1002&v=1spoWKM2fZ0', 'video_id' => "1spoWKM2fZ0", 'video_description' => ""));
$ListLinePlottoGiveaNMRSpectrum = Topic::create(array('topic_name' => "Chem 5 - List Line Plot to Give a NMR Spectrum", 'video_url' => 'https://www.youtube.com/watch?start=1108&v=1spoWKM2fZ0', 'video_id' => "1spoWKM2fZ0", 'video_description' => ""));
$Lesson9OnlineNotes = Topic::create(array('topic_name' => "Chem 5 - Lesson 9 Online Notes", 'video_url' => 'https://www.youtube.com/watch?start=1477&v=1spoWKM2fZ0', 'video_id' => "1spoWKM2fZ0", 'video_description' => ""));
$StructureFactors = Topic::create(array('topic_name' => "Chem 5 - Structure Factors", 'video_url' => 'https://www.youtube.com/watch?start=1971&v=1spoWKM2fZ0', 'video_id' => "1spoWKM2fZ0", 'video_description' => ""));
$Vectors = Topic::create(array('topic_name' => "Chem 5 - Vectors", 'video_url' => 'https://www.youtube.com/watch?start=265&v=oBFqwxnn2ek', 'video_id' => "oBFqwxnn2ek", 'video_description' => ""));
$MathWithVectors = Topic::create(array('topic_name' => "Chem 5 - Math With Vectors", 'video_url' => 'https://www.youtube.com/watch?start=1028&v=oBFqwxnn2ek', 'video_id' => "oBFqwxnn2ek", 'video_description' => ""));
$NormalizingVectors = Topic::create(array('topic_name' => "Chem 5 - Normalizing Vectors", 'video_url' => 'https://www.youtube.com/watch?start=1341&v=oBFqwxnn2ek', 'video_id' => "oBFqwxnn2ek", 'video_description' => ""));
$VectorDerivatives = Topic::create(array('topic_name' => "Chem 5 - Vector Derivatives", 'video_url' => 'https://www.youtube.com/watch?start=1801&v=oBFqwxnn2ek', 'video_id' => "oBFqwxnn2ek", 'video_description' => ""));
$VectorAnalysisPackage = Topic::create(array('topic_name' => "Chem 5 - Vector Analysis Package", 'video_url' => 'https://www.youtube.com/watch?start=2772&v=oBFqwxnn2ek', 'video_id' => "oBFqwxnn2ek", 'video_description' => ""));
$Gradient = Topic::create(array('topic_name' => "Chem 5 - Gradient", 'video_url' => 'https://www.youtube.com/watch?start=2962&v=oBFqwxnn2ek', 'video_id' => "oBFqwxnn2ek", 'video_description' => ""));
$Laplacian = Topic::create(array('topic_name' => "Chem 5 - Laplacian", 'video_url' => 'https://www.youtube.com/watch?start=3079&v=oBFqwxnn2ek', 'video_id' => "oBFqwxnn2ek", 'video_description' => ""));
$Curl = Topic::create(array('topic_name' => "Chem 5 - Curl", 'video_url' => 'https://www.youtube.com/watch?start=3258&v=oBFqwxnn2ek', 'video_id' => "oBFqwxnn2ek", 'video_description' => ""));
$MatrixForm = Topic::create(array('topic_name' => "Chem 5 - Matrix Form", 'video_url' => 'https://www.youtube.com/watch?start=3410&v=oBFqwxnn2ek', 'video_id' => "oBFqwxnn2ek", 'video_description' => ""));
$MultiplyingaMatrixbyaMatrix = Topic::create(array('topic_name' => "Chem 5 - Multiplying a Matrix by a Matrix", 'video_url' => 'https://www.youtube.com/watch?start=3788&v=oBFqwxnn2ek', 'video_id' => "oBFqwxnn2ek", 'video_description' => ""));
$MultiplyingaMatrixbyaVector = Topic::create(array('topic_name' => "Chem 5 - Multiplying a Matrix by a Vector", 'video_url' => 'https://www.youtube.com/watch?start=4113&v=oBFqwxnn2ek', 'video_id' => "oBFqwxnn2ek", 'video_description' => ""));
$Determinate = Topic::create(array('topic_name' => "Chem 5 - Determinate", 'video_url' => 'https://www.youtube.com/watch?start=4418&v=oBFqwxnn2ek', 'video_id' => "oBFqwxnn2ek", 'video_description' => ""));
$Inverse = Topic::create(array('topic_name' => "Chem 5 - Inverse", 'video_url' => 'https://www.youtube.com/watch?start=4481&v=oBFqwxnn2ek', 'video_id' => "oBFqwxnn2ek", 'video_description' => ""));
$FinishingMatrixManipulations = Topic::create(array('topic_name' => "Chem 5 - Finishing Matrix Manipulations", 'video_url' => 'https://www.youtube.com/watch?start=35&v=CaLzjesU-s8', 'video_id' => "CaLzjesU-s8", 'video_description' => ""));
$Eigenvalueproblem = Topic::create(array('topic_name' => "Chem 5 - Eigenvalue problem", 'video_url' => 'https://www.youtube.com/watch?start=685&v=CaLzjesU-s8', 'video_id' => "CaLzjesU-s8", 'video_description' => ""));
$MathematicaLesson10 = Topic::create(array('topic_name' => "Chem 5 - Mathematica Lesson 10", 'video_url' => 'https://www.youtube.com/watch?start=2314&v=CaLzjesU-s8', 'video_id' => "CaLzjesU-s8", 'video_description' => ""));
$ErrorCorrection = Topic::create(array('topic_name' => "Chem 5 - Error Correction", 'video_url' => 'https://www.youtube.com/watch?start=11&v=fTB-ENRptz8', 'video_id' => "fTB-ENRptz8", 'video_description' => ""));
$MolecularOrbitalsandEignevalueProblems = Topic::create(array('topic_name' => "Chem 5 - Molecular Orbitals and Eignevalue Problems", 'video_url' => 'https://www.youtube.com/watch?start=678&v=fTB-ENRptz8', 'video_id' => "fTB-ENRptz8", 'video_description' => ""));
$HuckelModel = Topic::create(array('topic_name' => "Chem 5 - Huckel Model", 'video_url' => 'https://www.youtube.com/watch?start=1038&v=fTB-ENRptz8', 'video_id' => "fTB-ENRptz8", 'video_description' => ""));
$EthyleneExample = Topic::create(array('topic_name' => "Chem 5 - Ethylene Example", 'video_url' => 'https://www.youtube.com/watch?start=1974&v=fTB-ENRptz8', 'video_id' => "fTB-ENRptz8", 'video_description' => ""));
$EnergyDiagram = Topic::create(array('topic_name' => "Chem 5 - Energy Diagram", 'video_url' => 'https://www.youtube.com/watch?start=2100&v=fTB-ENRptz8', 'video_id' => "fTB-ENRptz8", 'video_description' => ""));
$FindingtheOrbitalCoefficients = Topic::create(array('topic_name' => "Chem 5 - Finding the Orbital Coefficients", 'video_url' => 'https://www.youtube.com/watch?start=2976&v=fTB-ENRptz8', 'video_id' => "fTB-ENRptz8", 'video_description' => ""));
$VisualizingOrbitals = Topic::create(array('topic_name' => "Chem 5 - Visualizing Orbitals", 'video_url' => 'https://www.youtube.com/watch?start=3512&v=fTB-ENRptz8', 'video_id' => "fTB-ENRptz8", 'video_description' => ""));
$AromaticStabilization = Topic::create(array('topic_name' => "Chem 5 - Aromatic Stabilization", 'video_url' => 'https://www.youtube.com/watch?start=4299&v=fTB-ENRptz8', 'video_id' => "fTB-ENRptz8", 'video_description' => ""));
$VibrationalSpectrum = Topic::create(array('topic_name' => "Chem 5 - Vibrational Spectrum", 'video_url' => 'https://www.youtube.com/watch?start=174&v=HGb9N22OUVE', 'video_id' => "HGb9N22OUVE", 'video_description' => ""));
$NormalModeAnalysis = Topic::create(array('topic_name' => "Chem 5 - Normal Mode Analysis", 'video_url' => 'https://www.youtube.com/watch?start=222&v=HGb9N22OUVE', 'video_id' => "HGb9N22OUVE", 'video_description' => ""));
$VibrationsasSimpleSprings = Topic::create(array('topic_name' => "Chem 5 - Vibrations as Simple Springs", 'video_url' => 'https://www.youtube.com/watch?start=553&v=HGb9N22OUVE', 'video_id' => "HGb9N22OUVE", 'video_description' => ""));
$PotentialEnergy = Topic::create(array('topic_name' => "Chem 5 - Potential Energy", 'video_url' => 'https://www.youtube.com/watch?start=800&v=HGb9N22OUVE', 'video_id' => "HGb9N22OUVE", 'video_description' => ""));
$EulerLagrangeEquations = Topic::create(array('topic_name' => "Chem 5 - Euler-Lagrange Equations", 'video_url' => 'https://www.youtube.com/watch?start=2310&v=HGb9N22OUVE', 'video_id' => "HGb9N22OUVE", 'video_description' => ""));
$NewtonsEquations = Topic::create(array('topic_name' => "Chem 5 - Newton's Equations", 'video_url' => 'https://www.youtube.com/watch?start=2968&v=HGb9N22OUVE', 'video_id' => "HGb9N22OUVE", 'video_description' => ""));
$AmplitudesofMotion = Topic::create(array('topic_name' => "Chem 5 - Amplitudes of Motion", 'video_url' => 'https://www.youtube.com/watch?start=3840&v=HGb9N22OUVE', 'video_id' => "HGb9N22OUVE", 'video_description' => ""));
$AnimatingStretches = Topic::create(array('topic_name' => "Chem 5 - Animating Stretches", 'video_url' => 'https://www.youtube.com/watch?start=4247&v=HGb9N22OUVE', 'video_id' => "HGb9N22OUVE", 'video_description' => ""));
$FrequencyDatabase = Topic::create(array('topic_name' => "Chem 5 - Frequency Database", 'video_url' => 'https://www.youtube.com/watch?start=90&v=2BgUBjQMhYE', 'video_id' => "2BgUBjQMhYE", 'video_description' => ""));
$ConvertingUnits = Topic::create(array('topic_name' => "Chem 5 - Converting Units", 'video_url' => 'https://www.youtube.com/watch?start=322&v=2BgUBjQMhYE', 'video_id' => "2BgUBjQMhYE", 'video_description' => ""));
$CurveFitting = Topic::create(array('topic_name' => "Chem 5 - Curve Fitting", 'video_url' => 'https://www.youtube.com/watch?start=1551&v=2BgUBjQMhYE', 'video_id' => "2BgUBjQMhYE", 'video_description' => ""));
$FittingDataonMathematica = Topic::create(array('topic_name' => "Chem 5 - Fitting Data on Mathematica", 'video_url' => 'https://www.youtube.com/watch?start=2012&v=2BgUBjQMhYE', 'video_id' => "2BgUBjQMhYE", 'video_description' => ""));
$NonlinearFitwithFineFit = Topic::create(array('topic_name' => "Chem 5 - Nonlinear Fit with Fine Fit", 'video_url' => 'https://www.youtube.com/watch?start=294&v=VJzdiy6lqd4', 'video_id' => "VJzdiy6lqd4", 'video_description' => ""));
$FittingParameters = Topic::create(array('topic_name' => "Chem 5 - Fitting Parameters", 'video_url' => 'https://www.youtube.com/watch?start=876&v=VJzdiy6lqd4', 'video_id' => "VJzdiy6lqd4", 'video_description' => ""));
$AnalyzingtheFittingParameters = Topic::create(array('topic_name' => "Chem 5 - Analyzing the Fitting Parameters", 'video_url' => 'https://www.youtube.com/watch?start=1807&v=VJzdiy6lqd4', 'video_id' => "VJzdiy6lqd4", 'video_description' => ""));
$LinearModelFit = Topic::create(array('topic_name' => "Chem 5 - Linear Model Fit", 'video_url' => 'https://www.youtube.com/watch?start=2171&v=VJzdiy6lqd4', 'video_id' => "VJzdiy6lqd4", 'video_description' => ""));
$ModelProperties = Topic::create(array('topic_name' => "Chem 5 - Model Properties", 'video_url' => 'https://www.youtube.com/watch?start=2358&v=VJzdiy6lqd4', 'video_id' => "VJzdiy6lqd4", 'video_description' => ""));
$ConfidenceLevel = Topic::create(array('topic_name' => "Chem 5 - Confidence Level", 'video_url' => 'https://www.youtube.com/watch?start=2809&v=VJzdiy6lqd4', 'video_id' => "VJzdiy6lqd4", 'video_description' => ""));
$NonlinearModelFit = Topic::create(array('topic_name' => "Chem 5 - Nonlinear Model Fit", 'video_url' => 'https://www.youtube.com/watch?start=3598&v=VJzdiy6lqd4', 'video_id' => "VJzdiy6lqd4", 'video_description' => ""));
$ImportingaFile = Topic::create(array('topic_name' => "Chem 5 - Importing a File", 'video_url' => 'https://www.youtube.com/watch?start=224&v=4iOcZ-Tt5hw', 'video_id' => "4iOcZ-Tt5hw", 'video_description' => ""));
$StatisticalAnalysis = Topic::create(array('topic_name' => "Chem 5 - Statistical Analysis", 'video_url' => 'https://www.youtube.com/watch?start=378&v=4iOcZ-Tt5hw', 'video_id' => "4iOcZ-Tt5hw", 'video_description' => ""));
$DoLoop = Topic::create(array('topic_name' => "Chem 5 - Do-Loop", 'video_url' => 'https://www.youtube.com/watch?start=614&v=4iOcZ-Tt5hw', 'video_id' => "4iOcZ-Tt5hw", 'video_description' => ""));
$ErrorBarPlot = Topic::create(array('topic_name' => "Chem 5 - Error Bar Plot", 'video_url' => 'https://www.youtube.com/watch?start=978&v=4iOcZ-Tt5hw', 'video_id' => "4iOcZ-Tt5hw", 'video_description' => ""));
$ComputableDataDocumentation = Topic::create(array('topic_name' => "Chem 5 - Computable Data Documentation", 'video_url' => 'https://www.youtube.com/watch?start=1197&v=4iOcZ-Tt5hw', 'video_id' => "4iOcZ-Tt5hw", 'video_description' => ""));
$ChemicalData = Topic::create(array('topic_name' => "Chem 5 - Chemical Data", 'video_url' => 'https://www.youtube.com/watch?start=1298&v=4iOcZ-Tt5hw', 'video_id' => "4iOcZ-Tt5hw", 'video_description' => ""));
$ProteinData = Topic::create(array('topic_name' => "Chem 5 - Protein Data", 'video_url' => 'https://www.youtube.com/watch?start=2071&v=4iOcZ-Tt5hw', 'video_id' => "4iOcZ-Tt5hw", 'video_description' => ""));
$WolframDemonstrationProject = Topic::create(array('topic_name' => "Chem 5 - Wolfram Demonstration Project", 'video_url' => 'https://www.youtube.com/watch?start=2431&v=4iOcZ-Tt5hw', 'video_id' => "4iOcZ-Tt5hw", 'video_description' => ""));
$DownloadingCDF = Topic::create(array('topic_name' => "Chem 5 - Downloading CDF", 'video_url' => 'https://www.youtube.com/watch?start=2812&v=4iOcZ-Tt5hw', 'video_id' => "4iOcZ-Tt5hw", 'video_description' => ""));
$OtherTopicsontheDemonstrationProject = Topic::create(array('topic_name' => "Chem 5 - Other Topics on the Demonstration Project", 'video_url' => 'https://www.youtube.com/watch?start=3117&v=4iOcZ-Tt5hw', 'video_id' => "4iOcZ-Tt5hw", 'video_description' => ""));
$CDFPlayer = Topic::create(array('topic_name' => "Chem 5 - CDF Player", 'video_url' => 'https://www.youtube.com/watch?start=3214&v=4iOcZ-Tt5hw', 'video_id' => "4iOcZ-Tt5hw", 'video_description' => ""));

    }
}
