<?php

use Illuminate\Database\Seeder;

use Illuminate\Database\Eloquent\Model;
use App\Keyword;
use App\Topic;
use App\Chemtext;
use App\Problem;
use App\Solution;

class Chem131ASeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
$Light = Topic::create(array('topic_name' => "Chem 131A - Light ", 'video_url' => 'https://www.youtube.com/watch?start=331&v=TgKkM0j42vs', 'video_id' => "TgKkM0j42vs", 'video_description' => ""));
$Quantization = Topic::create(array('topic_name' => "Chem 131A - Quantization", 'video_url' => 'https://www.youtube.com/watch?start=725&v=TgKkM0j42vs', 'video_id' => "TgKkM0j42vs", 'video_description' => ""));
$ThePhotoelectricEffect = Topic::create(array('topic_name' => "Chem 131A - The Photoelectric Effect", 'video_url' => 'https://www.youtube.com/watch?start=1150&v=TgKkM0j42vs', 'video_id' => "TgKkM0j42vs", 'video_description' => ""));
$PhotonMomentum = Topic::create(array('topic_name' => "Chem 131A - Photon Momentum", 'video_url' => 'https://www.youtube.com/watch?start=1739&v=TgKkM0j42vs', 'video_id' => "TgKkM0j42vs", 'video_description' => ""));
$LouisdeBroglie = Topic::create(array('topic_name' => "Chem 131A - Louis de Broglie", 'video_url' => 'https://www.youtube.com/watch?start=20&v=HI39yFQ1SIw', 'video_id' => "HI39yFQ1SIw", 'video_description' => ""));
$WhereistheParticle = Topic::create(array('topic_name' => "Chem 131A - Where is the Particle?", 'video_url' => 'https://www.youtube.com/watch?start=152&v=HI39yFQ1SIw', 'video_id' => "HI39yFQ1SIw", 'video_description' => ""));
$Waves = Topic::create(array('topic_name' => "Chem 131A - Waves", 'video_url' => 'https://www.youtube.com/watch?start=889&v=HI39yFQ1SIw', 'video_id' => "HI39yFQ1SIw", 'video_description' => ""));
$PracticeProblem4deBrogliewavelength = Topic::create(array('topic_name' => "Chem 131A - Practice Problem 4: de Broglie wavelength", 'video_url' => 'https://www.youtube.com/watch?start=1160&v=HI39yFQ1SIw', 'video_id' => "HI39yFQ1SIw", 'video_description' => ""));
$Wavefunctions = Topic::create(array('topic_name' => "Chem 131A - Wavefunctions", 'video_url' => 'https://www.youtube.com/watch?start=1276&v=HI39yFQ1SIw', 'video_id' => "HI39yFQ1SIw", 'video_description' => ""));
$ThePostulatesofQM = Topic::create(array('topic_name' => "Chem 131A - The Postulates of QM", 'video_url' => 'https://www.youtube.com/watch?start=1756&v=HI39yFQ1SIw', 'video_id' => "HI39yFQ1SIw", 'video_description' => ""));
$ThePostulatesofQM = Topic::create(array('topic_name' => "Chem 131A - The Postulates of QM", 'video_url' => 'https://www.youtube.com/watch?start=19&v=5QZ7ROTfIYU', 'video_id' => "5QZ7ROTfIYU", 'video_description' => ""));
$TheMomentumOperator = Topic::create(array('topic_name' => "Chem 131A - The Momentum Operator", 'video_url' => 'https://www.youtube.com/watch?start=330&v=5QZ7ROTfIYU', 'video_id' => "5QZ7ROTfIYU", 'video_description' => ""));
$BasicFunctions = Topic::create(array('topic_name' => "Chem 131A - Basic Functions", 'video_url' => 'https://www.youtube.com/watch?start=497&v=5QZ7ROTfIYU', 'video_id' => "5QZ7ROTfIYU", 'video_description' => ""));
$Orthogonality = Topic::create(array('topic_name' => "Chem 131A - Orthogonality", 'video_url' => 'https://www.youtube.com/watch?start=824&v=5QZ7ROTfIYU', 'video_id' => "5QZ7ROTfIYU", 'video_description' => ""));
$Uncertainty = Topic::create(array('topic_name' => "Chem 131A - Uncertainty", 'video_url' => 'https://www.youtube.com/watch?start=1730&v=5QZ7ROTfIYU', 'video_id' => "5QZ7ROTfIYU", 'video_description' => ""));
$Complementarity = Topic::create(array('topic_name' => "Chem 131A - Complementarity", 'video_url' => 'https://www.youtube.com/watch?start=1851&v=5QZ7ROTfIYU', 'video_id' => "5QZ7ROTfIYU", 'video_description' => ""));
$ClassicalAtoms = Topic::create(array('topic_name' => "Chem 131A - Classical Atoms", 'video_url' => 'https://www.youtube.com/watch?start=2100&v=5QZ7ROTfIYU', 'video_id' => "5QZ7ROTfIYU", 'video_description' => ""));
$WavefunctionsandOrbitals = Topic::create(array('topic_name' => "Chem 131A - Wavefunctions and Orbitals", 'video_url' => 'https://www.youtube.com/watch?start=2352&v=5QZ7ROTfIYU', 'video_id' => "5QZ7ROTfIYU", 'video_description' => ""));
$ConfinedSystems = Topic::create(array('topic_name' => "Chem 131A - Confined Systems", 'video_url' => 'https://www.youtube.com/watch?start=2617&v=5QZ7ROTfIYU', 'video_id' => "5QZ7ROTfIYU", 'video_description' => ""));
$ThePositionOperator = Topic::create(array('topic_name' => "Chem 131A - The Position Operator", 'video_url' => 'https://www.youtube.com/watch?start=2749&v=5QZ7ROTfIYU', 'video_id' => "5QZ7ROTfIYU", 'video_description' => ""));
$LocalizedWavefunctions = Topic::create(array('topic_name' => "Chem 131A - Localized Wavefunctions", 'video_url' => 'https://www.youtube.com/watch?start=20&v=lPeMYaamDvQ', 'video_id' => "lPeMYaamDvQ", 'video_description' => ""));
$FourierSeries = Topic::create(array('topic_name' => "Chem 131A - Fourier Series", 'video_url' => 'https://www.youtube.com/watch?start=690&v=lPeMYaamDvQ', 'video_id' => "lPeMYaamDvQ", 'video_description' => ""));
$QuantumCryptography = Topic::create(array('topic_name' => "Chem 131A - Quantum Cryptography", 'video_url' => 'https://www.youtube.com/watch?start=801&v=lPeMYaamDvQ', 'video_id' => "lPeMYaamDvQ", 'video_description' => ""));
$TimeEvolution = Topic::create(array('topic_name' => "Chem 131A - Time Evolution", 'video_url' => 'https://www.youtube.com/watch?start=1712&v=lPeMYaamDvQ', 'video_id' => "lPeMYaamDvQ", 'video_description' => ""));
$AFreeParticle = Topic::create(array('topic_name' => "Chem 131A - A Free Particle", 'video_url' => 'https://www.youtube.com/watch?start=2842&v=lPeMYaamDvQ', 'video_id' => "lPeMYaamDvQ", 'video_description' => ""));
$TheBox = Topic::create(array('topic_name' => "Chem 131A - The Box", 'video_url' => 'https://www.youtube.com/watch?start=20&v=HiEgMEU64LA', 'video_id' => "HiEgMEU64LA", 'video_description' => ""));
$TheWavefunction = Topic::create(array('topic_name' => "Chem 131A - The Wavefunction", 'video_url' => 'https://www.youtube.com/watch?start=269&v=HiEgMEU64LA', 'video_id' => "HiEgMEU64LA", 'video_description' => ""));
$Normalization = Topic::create(array('topic_name' => "Chem 131A - Normalization", 'video_url' => 'https://www.youtube.com/watch?start=1162&v=HiEgMEU64LA', 'video_id' => "HiEgMEU64LA", 'video_description' => ""));
$Interpretation = Topic::create(array('topic_name' => "Chem 131A - Interpretation", 'video_url' => 'https://www.youtube.com/watch?start=1707&v=HiEgMEU64LA', 'video_id' => "HiEgMEU64LA", 'video_description' => ""));
$ExpectationValues = Topic::create(array('topic_name' => "Chem 131A - Expectation Values", 'video_url' => 'https://www.youtube.com/watch?start=1910&v=HiEgMEU64LA', 'video_id' => "HiEgMEU64LA", 'video_description' => ""));
$ExcitedStates = Topic::create(array('topic_name' => "Chem 131A - Excited States", 'video_url' => 'https://www.youtube.com/watch?start=2759&v=HiEgMEU64LA', 'video_id' => "HiEgMEU64LA", 'video_description' => ""));
$WavefunctionPlots = Topic::create(array('topic_name' => "Chem 131A - Wavefunction Plots", 'video_url' => 'https://www.youtube.com/watch?start=2859&v=HiEgMEU64LA', 'video_id' => "HiEgMEU64LA", 'video_description' => ""));
$Tunneling = Topic::create(array('topic_name' => "Chem 131A - Tunneling", 'video_url' => 'https://www.youtube.com/watch?start=42&v=mGlAKV7h2S8', 'video_id' => "mGlAKV7h2S8", 'video_description' => ""));
$BarrierPenetration = Topic::create(array('topic_name' => "Chem 131A - Barrier Penetration", 'video_url' => 'https://www.youtube.com/watch?start=1782&v=mGlAKV7h2S8', 'video_id' => "mGlAKV7h2S8", 'video_description' => ""));
$Tunneling = Topic::create(array('topic_name' => "Chem 131A - Tunneling", 'video_url' => 'https://www.youtube.com/watch?start=1857&v=mGlAKV7h2S8', 'video_id' => "mGlAKV7h2S8", 'video_description' => ""));
$Interpretation = Topic::create(array('topic_name' => "Chem 131A - Interpretation", 'video_url' => 'https://www.youtube.com/watch?start=2674&v=mGlAKV7h2S8', 'video_id' => "mGlAKV7h2S8", 'video_description' => ""));
$STM = Topic::create(array('topic_name' => "Chem 131A - STM", 'video_url' => 'https://www.youtube.com/watch?start=207&v=3cAGARO-JVY', 'video_id' => "3cAGARO-JVY", 'video_description' => ""));
$Vibrations = Topic::create(array('topic_name' => "Chem 131A - Vibrations", 'video_url' => 'https://www.youtube.com/watch?start=1159&v=3cAGARO-JVY', 'video_id' => "3cAGARO-JVY", 'video_description' => ""));
$ZeroPointEnergy = Topic::create(array('topic_name' => "Chem 131A - Zero-Point Energy", 'video_url' => 'https://www.youtube.com/watch?start=2793&v=3cAGARO-JVY', 'video_id' => "3cAGARO-JVY", 'video_description' => ""));
$IsotopeEffects = Topic::create(array('topic_name' => "Chem 131A - Isotope Effects", 'video_url' => 'https://www.youtube.com/watch?start=2959&v=3cAGARO-JVY', 'video_id' => "3cAGARO-JVY", 'video_description' => ""));
$VibrationalEnergyLevels = Topic::create(array('topic_name' => "Chem 131A - Vibrational Energy Levels", 'video_url' => 'https://www.youtube.com/watch?start=83&v=6PQOkRRF2uw', 'video_id' => "6PQOkRRF2uw", 'video_description' => ""));
$PropertiesofOscillators = Topic::create(array('topic_name' => "Chem 131A - Properties of Oscillators", 'video_url' => 'https://www.youtube.com/watch?start=1175&v=6PQOkRRF2uw', 'video_id' => "6PQOkRRF2uw", 'video_description' => ""));
$PerturbationTheory = Topic::create(array('topic_name' => "Chem 131A - Perturbation Theory", 'video_url' => 'https://www.youtube.com/watch?start=1603&v=6PQOkRRF2uw', 'video_id' => "6PQOkRRF2uw", 'video_description' => ""));
$IntroducingLambda = Topic::create(array('topic_name' => "Chem 131A - Introducing Lambda", 'video_url' => 'https://www.youtube.com/watch?start=2438&v=6PQOkRRF2uw', 'video_id' => "6PQOkRRF2uw", 'video_description' => ""));
$CorrectingtheEnergy = Topic::create(array('topic_name' => "Chem 131A - Correcting the Energy", 'video_url' => 'https://www.youtube.com/watch?start=2562&v=6PQOkRRF2uw', 'video_id' => "6PQOkRRF2uw", 'video_description' => ""));
$AnExampleVanishingWavefunction = Topic::create(array('topic_name' => "Chem 131A - An Example: Vanishing Wavefunction", 'video_url' => 'https://www.youtube.com/watch?start=3047&v=6PQOkRRF2uw', 'video_id' => "6PQOkRRF2uw", 'video_description' => ""));
$OddorAntisymmetricFunctions = Topic::create(array('topic_name' => "Chem 131A - Odd, or Antisymmetric, Functions", 'video_url' => 'https://www.youtube.com/watch?start=62&v=2LsKFN-N32k', 'video_id' => "2LsKFN-N32k", 'video_description' => ""));
$TheMorsePotential = Topic::create(array('topic_name' => "Chem 131A - The Morse Potential", 'video_url' => 'https://www.youtube.com/watch?start=357&v=2LsKFN-N32k', 'video_id' => "2LsKFN-N32k", 'video_description' => ""));
$The612Potential = Topic::create(array('topic_name' => "Chem 131A - The 6 - 12 Potential", 'video_url' => 'https://www.youtube.com/watch?start=1085&v=2LsKFN-N32k', 'video_id' => "2LsKFN-N32k", 'video_description' => ""));
$QuantumSystemsin2Dand3D = Topic::create(array('topic_name' => "Chem 131A - Quantum Systems in 2D and 3D", 'video_url' => 'https://www.youtube.com/watch?start=1648&v=2LsKFN-N32k', 'video_id' => "2LsKFN-N32k", 'video_description' => ""));
$Particleina2DBox = Topic::create(array('topic_name' => "Chem 131A - Particle in a 2D Box", 'video_url' => 'https://www.youtube.com/watch?start=1721&v=2LsKFN-N32k', 'video_id' => "2LsKFN-N32k", 'video_description' => ""));
$QuantumDots = Topic::create(array('topic_name' => "Chem 131A - Quantum Dots", 'video_url' => 'https://www.youtube.com/watch?start=2389&v=2LsKFN-N32k', 'video_id' => "2LsKFN-N32k", 'video_description' => ""));
$Degeneracy = Topic::create(array('topic_name' => "Chem 131A - Degeneracy", 'video_url' => 'https://www.youtube.com/watch?start=2560&v=2LsKFN-N32k', 'video_id' => "2LsKFN-N32k", 'video_description' => ""));
$Symmetry = Topic::create(array('topic_name' => "Chem 131A - Symmetry", 'video_url' => 'https://www.youtube.com/watch?start=2680&v=2LsKFN-N32k', 'video_id' => "2LsKFN-N32k", 'video_description' => ""));
$ParticleonaRing = Topic::create(array('topic_name' => "Chem 131A - Particle on a Ring", 'video_url' => 'https://www.youtube.com/watch?start=143&v=T-FWVIBmxIU', 'video_id' => "T-FWVIBmxIU", 'video_description' => ""));
$Quantization = Topic::create(array('topic_name' => "Chem 131A - Quantization", 'video_url' => 'https://www.youtube.com/watch?start=1009&v=T-FWVIBmxIU', 'video_id' => "T-FWVIBmxIU", 'video_description' => ""));
$PreparationforAtoms = Topic::create(array('topic_name' => "Chem 131A - Preparation for Atoms", 'video_url' => 'https://www.youtube.com/watch?start=1463&v=T-FWVIBmxIU', 'video_id' => "T-FWVIBmxIU", 'video_description' => ""));
$SpehericalPolarCoordinates = Topic::create(array('topic_name' => "Chem 131A - Speherical Polar Coordinates", 'video_url' => 'https://www.youtube.com/watch?start=1636&v=T-FWVIBmxIU', 'video_id' => "T-FWVIBmxIU", 'video_description' => ""));
$ParticleonaSphere = Topic::create(array('topic_name' => "Chem 131A - Particle on a Sphere", 'video_url' => 'https://www.youtube.com/watch?start=1878&v=T-FWVIBmxIU', 'video_id' => "T-FWVIBmxIU", 'video_description' => ""));
$TheLegendrian = Topic::create(array('topic_name' => "Chem 131A - The Legendrian", 'video_url' => 'https://www.youtube.com/watch?start=1983&v=T-FWVIBmxIU', 'video_id' => "T-FWVIBmxIU", 'video_description' => ""));
$SphericalPolarCoordinates = Topic::create(array('topic_name' => "Chem 131A - Spherical Polar Coordinates", 'video_url' => 'https://www.youtube.com/watch?start=2106&v=T-FWVIBmxIU', 'video_id' => "T-FWVIBmxIU", 'video_description' => ""));
$TheSolutioninPhi = Topic::create(array('topic_name' => "Chem 131A - The Solution in Phi", 'video_url' => 'https://www.youtube.com/watch?start=107&v=8v_hTtqkwdU', 'video_id' => "8v_hTtqkwdU", 'video_description' => ""));
$TheSolutioninTheta = Topic::create(array('topic_name' => "Chem 131A - The Solution in Theta", 'video_url' => 'https://www.youtube.com/watch?start=190&v=8v_hTtqkwdU', 'video_id' => "8v_hTtqkwdU", 'video_description' => ""));
$EnergyQuantization = Topic::create(array('topic_name' => "Chem 131A - Energy Quantization", 'video_url' => 'https://www.youtube.com/watch?start=1451&v=8v_hTtqkwdU', 'video_id' => "8v_hTtqkwdU", 'video_description' => ""));
$TheSphericalHarmonics = Topic::create(array('topic_name' => "Chem 131A - The Spherical Harmonics", 'video_url' => 'https://www.youtube.com/watch?start=1841&v=8v_hTtqkwdU', 'video_id' => "8v_hTtqkwdU", 'video_description' => ""));
$Transitions = Topic::create(array('topic_name' => "Chem 131A - Transitions", 'video_url' => 'https://www.youtube.com/watch?start=2006&v=8v_hTtqkwdU', 'video_id' => "8v_hTtqkwdU", 'video_description' => ""));
$Spin = Topic::create(array('topic_name' => "Chem 131A - Spin", 'video_url' => 'https://www.youtube.com/watch?start=2240&v=8v_hTtqkwdU', 'video_id' => "8v_hTtqkwdU", 'video_description' => ""));
$SternGerlachExperiment = Topic::create(array('topic_name' => "Chem 131A - Stern-Gerlach Experiment", 'video_url' => 'https://www.youtube.com/watch?start=2541&v=8v_hTtqkwdU', 'video_id' => "8v_hTtqkwdU", 'video_description' => ""));
$ElectronSpin = Topic::create(array('topic_name' => "Chem 131A - Electron Spin", 'video_url' => 'https://www.youtube.com/watch?start=2891&v=8v_hTtqkwdU', 'video_id' => "8v_hTtqkwdU", 'video_description' => ""));
$Spin = Topic::create(array('topic_name' => "Chem 131A - Spin", 'video_url' => 'https://www.youtube.com/watch?start=22&v=Yfkt3oSeARQ', 'video_id' => "Yfkt3oSeARQ", 'video_description' => ""));
$TheVectorModel = Topic::create(array('topic_name' => "Chem 131A - The Vector Model", 'video_url' => 'https://www.youtube.com/watch?start=176&v=Yfkt3oSeARQ', 'video_id' => "Yfkt3oSeARQ", 'video_description' => ""));
$TheCommutator = Topic::create(array('topic_name' => "Chem 131A - The Commutator", 'video_url' => 'https://www.youtube.com/watch?start=666&v=Yfkt3oSeARQ', 'video_id' => "Yfkt3oSeARQ", 'video_description' => ""));
$Wavenumbers = Topic::create(array('topic_name' => "Chem 131A - Wavenumbers", 'video_url' => 'https://www.youtube.com/watch?start=1345&v=Yfkt3oSeARQ', 'video_id' => "Yfkt3oSeARQ", 'video_description' => ""));
$AtomicSpectroscopy = Topic::create(array('topic_name' => "Chem 131A - Atomic Spectroscopy", 'video_url' => 'https://www.youtube.com/watch?start=1785&v=Yfkt3oSeARQ', 'video_id' => "Yfkt3oSeARQ", 'video_description' => ""));
$TheHamiltonianWavefunction = Topic::create(array('topic_name' => "Chem 131A - The Hamiltonian Wavefunction", 'video_url' => 'https://www.youtube.com/watch?start=2074&v=Yfkt3oSeARQ', 'video_id' => "Yfkt3oSeARQ", 'video_description' => ""));
$SeparationofVariables = Topic::create(array('topic_name' => "Chem 131A - Separation of Variables", 'video_url' => 'https://www.youtube.com/watch?start=2572&v=Yfkt3oSeARQ', 'video_id' => "Yfkt3oSeARQ", 'video_description' => ""));
$TheRadialFunctions = Topic::create(array('topic_name' => "Chem 131A - The Radial Functions", 'video_url' => 'https://www.youtube.com/watch?start=57&v=k71Z1P8bX-c', 'video_id' => "k71Z1P8bX-c", 'video_description' => ""));
$TheRydbergConstant = Topic::create(array('topic_name' => "Chem 131A - The Rydberg Constant", 'video_url' => 'https://www.youtube.com/watch?start=432&v=k71Z1P8bX-c', 'video_id' => "k71Z1P8bX-c", 'video_description' => ""));
$TheBohrRadius = Topic::create(array('topic_name' => "Chem 131A - The Bohr Radius", 'video_url' => 'https://www.youtube.com/watch?start=819&v=k71Z1P8bX-c', 'video_id' => "k71Z1P8bX-c", 'video_description' => ""));
$Notation = Topic::create(array('topic_name' => "Chem 131A - Notation", 'video_url' => 'https://www.youtube.com/watch?start=1374&v=k71Z1P8bX-c', 'video_id' => "k71Z1P8bX-c", 'video_description' => ""));
$TheWavefunctions = Topic::create(array('topic_name' => "Chem 131A - The Wavefunctions", 'video_url' => 'https://www.youtube.com/watch?start=1615&v=k71Z1P8bX-c', 'video_id' => "k71Z1P8bX-c", 'video_description' => ""));
$RadialNodes = Topic::create(array('topic_name' => "Chem 131A - Radial Nodes", 'video_url' => 'https://www.youtube.com/watch?start=1919&v=k71Z1P8bX-c', 'video_id' => "k71Z1P8bX-c", 'video_description' => ""));
$IntegratingWavefunctions = Topic::create(array('topic_name' => "Chem 131A - Integrating Wavefunctions", 'video_url' => 'https://www.youtube.com/watch?start=2204&v=k71Z1P8bX-c', 'video_id' => "k71Z1P8bX-c", 'video_description' => ""));
$AtomicSpectroscopy = Topic::create(array('topic_name' => "Chem 131A - Atomic Spectroscopy", 'video_url' => 'https://www.youtube.com/watch?start=41&v=x--RtwuNUw4', 'video_id' => "x--RtwuNUw4", 'video_description' => ""));
$EmissionSpectra = Topic::create(array('topic_name' => "Chem 131A - Emission Spectra", 'video_url' => 'https://www.youtube.com/watch?start=548&v=x--RtwuNUw4', 'video_id' => "x--RtwuNUw4", 'video_description' => ""));
$CouplingSchemes = Topic::create(array('topic_name' => "Chem 131A - Coupling Schemes", 'video_url' => 'https://www.youtube.com/watch?start=1301&v=x--RtwuNUw4', 'video_id' => "x--RtwuNUw4", 'video_description' => ""));
$LSCoupling = Topic::create(array('topic_name' => "Chem 131A - LS Coupling", 'video_url' => 'https://www.youtube.com/watch?start=1577&v=x--RtwuNUw4', 'video_id' => "x--RtwuNUw4", 'video_description' => ""));
$AddingAngularMomenta = Topic::create(array('topic_name' => "Chem 131A - Adding Angular Momenta", 'video_url' => 'https://www.youtube.com/watch?start=1782&v=x--RtwuNUw4', 'video_id' => "x--RtwuNUw4", 'video_description' => ""));
$VectorModelForCoupling = Topic::create(array('topic_name' => "Chem 131A - Vector Model For Coupling", 'video_url' => 'https://www.youtube.com/watch?start=1907&v=x--RtwuNUw4', 'video_id' => "x--RtwuNUw4", 'video_description' => ""));
$SymmetryConsiderations = Topic::create(array('topic_name' => "Chem 131A - Symmetry Considerations", 'video_url' => 'https://www.youtube.com/watch?start=2320&v=x--RtwuNUw4', 'video_id' => "x--RtwuNUw4", 'video_description' => ""));
$LSCoupling = Topic::create(array('topic_name' => "Chem 131A - LS Coupling", 'video_url' => 'https://www.youtube.com/watch?start=2508&v=x--RtwuNUw4', 'video_id' => "x--RtwuNUw4", 'video_description' => ""));
$TermSymbols = Topic::create(array('topic_name' => "Chem 131A - Term Symbols", 'video_url' => 'https://www.youtube.com/watch?start=2668&v=x--RtwuNUw4', 'video_id' => "x--RtwuNUw4", 'video_description' => ""));
$SelectionRules = Topic::create(array('topic_name' => "Chem 131A - Selection Rules", 'video_url' => 'https://www.youtube.com/watch?start=3032&v=x--RtwuNUw4', 'video_id' => "x--RtwuNUw4", 'video_description' => ""));
$QuantumNumbers = Topic::create(array('topic_name' => "Chem 131A - Quantum Numbers", 'video_url' => 'https://www.youtube.com/watch?start=21&v=939VMKRlKMs', 'video_id' => "939VMKRlKMs", 'video_description' => ""));
$Configurations = Topic::create(array('topic_name' => "Chem 131A - Configurations", 'video_url' => 'https://www.youtube.com/watch?start=160&v=939VMKRlKMs', 'video_id' => "939VMKRlKMs", 'video_description' => ""));
$TermSymbols = Topic::create(array('topic_name' => "Chem 131A - Term Symbols", 'video_url' => 'https://www.youtube.com/watch?start=272&v=939VMKRlKMs', 'video_id' => "939VMKRlKMs", 'video_description' => ""));
$HolesandElectrons = Topic::create(array('topic_name' => "Chem 131A - Holes and Electrons", 'video_url' => 'https://www.youtube.com/watch?start=722&v=939VMKRlKMs', 'video_id' => "939VMKRlKMs", 'video_description' => ""));
$ShapesofHWavefunctions = Topic::create(array('topic_name' => "Chem 131A - Shapes of H Wavefunctions", 'video_url' => 'https://www.youtube.com/watch?start=827&v=939VMKRlKMs', 'video_id' => "939VMKRlKMs", 'video_description' => ""));
$HydrogenOrbitals = Topic::create(array('topic_name' => "Chem 131A - Hydrogen Orbitals", 'video_url' => 'https://www.youtube.com/watch?start=1059&v=939VMKRlKMs', 'video_id' => "939VMKRlKMs", 'video_description' => ""));
$Nodes = Topic::create(array('topic_name' => "Chem 131A - Nodes", 'video_url' => 'https://www.youtube.com/watch?start=1121&v=939VMKRlKMs', 'video_id' => "939VMKRlKMs", 'video_description' => ""));
$SpinOrbitCoupling = Topic::create(array('topic_name' => "Chem 131A - Spin-Orbit Coupling", 'video_url' => 'https://www.youtube.com/watch?start=1385&v=939VMKRlKMs', 'video_id' => "939VMKRlKMs", 'video_description' => ""));
$InternalMagneticField = Topic::create(array('topic_name' => "Chem 131A - Internal Magnetic Field", 'video_url' => 'https://www.youtube.com/watch?start=1449&v=939VMKRlKMs', 'video_id' => "939VMKRlKMs", 'video_description' => ""));
$OtherAlkaliMetals = Topic::create(array('topic_name' => "Chem 131A - Other Alkali Metals", 'video_url' => 'https://www.youtube.com/watch?start=1943&v=939VMKRlKMs', 'video_id' => "939VMKRlKMs", 'video_description' => ""));
$Cesium = Topic::create(array('topic_name' => "Chem 131A - Cesium", 'video_url' => 'https://www.youtube.com/watch?start=2242&v=939VMKRlKMs', 'video_id' => "939VMKRlKMs", 'video_description' => ""));
$Cesium = Topic::create(array('topic_name' => "Chem 131A - Cesium", 'video_url' => 'https://www.youtube.com/watch?start=51&v=6My91e7qFFg', 'video_id' => "6My91e7qFFg", 'video_description' => ""));
$AnotherLookAtSpinOrbitCoupling = Topic::create(array('topic_name' => "Chem 131A - Another Look At Spin-Orbit Coupling", 'video_url' => 'https://www.youtube.com/watch?start=1177&v=6My91e7qFFg', 'video_id' => "6My91e7qFFg", 'video_description' => ""));
$TheEnergyShift = Topic::create(array('topic_name' => "Chem 131A - The Energy Shift", 'video_url' => 'https://www.youtube.com/watch?start=1422&v=6My91e7qFFg', 'video_id' => "6My91e7qFFg", 'video_description' => ""));
$TwoElectronAtoms = Topic::create(array('topic_name' => "Chem 131A - Two-Electron Atoms", 'video_url' => 'https://www.youtube.com/watch?start=1500&v=6My91e7qFFg', 'video_id' => "6My91e7qFFg", 'video_description' => ""));
$ThePauliPrinciple = Topic::create(array('topic_name' => "Chem 131A - The Pauli Principle", 'video_url' => 'https://www.youtube.com/watch?start=2226&v=6My91e7qFFg', 'video_id' => "6My91e7qFFg", 'video_description' => ""));
$SpinandSpace = Topic::create(array('topic_name' => "Chem 131A - Spin and Space", 'video_url' => 'https://www.youtube.com/watch?start=2491&v=6My91e7qFFg', 'video_id' => "6My91e7qFFg", 'video_description' => ""));
$Symmetry = Topic::create(array('topic_name' => "Chem 131A - Symmetry", 'video_url' => 'https://www.youtube.com/watch?start=55&v=gqf3nEdHoYE', 'video_id' => "gqf3nEdHoYE", 'video_description' => ""));
$Orthogonality = Topic::create(array('topic_name' => "Chem 131A - Orthogonality", 'video_url' => 'https://www.youtube.com/watch?start=143&v=gqf3nEdHoYE', 'video_id' => "gqf3nEdHoYE", 'video_description' => ""));
$TheVariationalPrinciple = Topic::create(array('topic_name' => "Chem 131A - The Variational Principle", 'video_url' => 'https://www.youtube.com/watch?start=353&v=gqf3nEdHoYE', 'video_id' => "gqf3nEdHoYE", 'video_description' => ""));
$AtomicUnits = Topic::create(array('topic_name' => "Chem 131A - Atomic Units", 'video_url' => 'https://www.youtube.com/watch?start=1397&v=gqf3nEdHoYE', 'video_id' => "gqf3nEdHoYE", 'video_description' => ""));
$Notation = Topic::create(array('topic_name' => "Chem 131A - Notation", 'video_url' => 'https://www.youtube.com/watch?start=2065&v=gqf3nEdHoYE', 'video_id' => "gqf3nEdHoYE", 'video_description' => ""));
$HydrideAnionTry1 = Topic::create(array('topic_name' => "Chem 131A - Hydride Anion, Try #1", 'video_url' => 'https://www.youtube.com/watch?start=2249&v=gqf3nEdHoYE', 'video_id' => "gqf3nEdHoYE", 'video_description' => ""));
$WhereWeLeftOff = Topic::create(array('topic_name' => "Chem 131A - Where We Left Off", 'video_url' => 'https://www.youtube.com/watch?start=53&v=i0pO9ljhLQ0', 'video_id' => "i0pO9ljhLQ0", 'video_description' => ""));
$Figuringr12 = Topic::create(array('topic_name' => "Chem 131A - Figuring r12", 'video_url' => 'https://www.youtube.com/watch?start=126&v=i0pO9ljhLQ0', 'video_id' => "i0pO9ljhLQ0", 'video_description' => ""));
$LawofCosines = Topic::create(array('topic_name' => "Chem 131A - Law of Cosines", 'video_url' => 'https://www.youtube.com/watch?start=235&v=i0pO9ljhLQ0', 'video_id' => "i0pO9ljhLQ0", 'video_description' => ""));
$FirstOrderCorrection = Topic::create(array('topic_name' => "Chem 131A - First-Order Correction", 'video_url' => 'https://www.youtube.com/watch?start=478&v=i0pO9ljhLQ0', 'video_id' => "i0pO9ljhLQ0", 'video_description' => ""));
$TheThetaIntegral = Topic::create(array('topic_name' => "Chem 131A - The Theta Integral", 'video_url' => 'https://www.youtube.com/watch?start=551&v=i0pO9ljhLQ0', 'video_id' => "i0pO9ljhLQ0", 'video_description' => ""));
$WhatstheEnergy = Topic::create(array('topic_name' => "Chem 131A - What's the Energy?", 'video_url' => 'https://www.youtube.com/watch?start=1062&v=i0pO9ljhLQ0', 'video_id' => "i0pO9ljhLQ0", 'video_description' => ""));
$StabilityofHydride = Topic::create(array('topic_name' => "Chem 131A - Stability of Hydride", 'video_url' => 'https://www.youtube.com/watch?start=1196&v=i0pO9ljhLQ0', 'video_id' => "i0pO9ljhLQ0", 'video_description' => ""));
$ImprovingOurEstimate = Topic::create(array('topic_name' => "Chem 131A - Improving Our Estimate", 'video_url' => 'https://www.youtube.com/watch?start=1477&v=i0pO9ljhLQ0', 'video_id' => "i0pO9ljhLQ0", 'video_description' => ""));
$EvaluatingtheEnergy = Topic::create(array('topic_name' => "Chem 131A - Evaluating the Energy", 'video_url' => 'https://www.youtube.com/watch?start=1819&v=i0pO9ljhLQ0', 'video_id' => "i0pO9ljhLQ0", 'video_description' => ""));
$TheRepulsionTerm = Topic::create(array('topic_name' => "Chem 131A - The Repulsion Term", 'video_url' => 'https://www.youtube.com/watch?start=2229&v=i0pO9ljhLQ0', 'video_id' => "i0pO9ljhLQ0", 'video_description' => ""));
$TheHeliumAtom = Topic::create(array('topic_name' => "Chem 131A - The Helium Atom", 'video_url' => 'https://www.youtube.com/watch?start=2639&v=i0pO9ljhLQ0', 'video_id' => "i0pO9ljhLQ0", 'video_description' => ""));
$HydrideTry3 = Topic::create(array('topic_name' => "Chem 131A - Hydride Try #3", 'video_url' => 'https://www.youtube.com/watch?start=38&v=9ZF4gnXv85o', 'video_id' => "9ZF4gnXv85o", 'video_description' => ""));
$TheOrbitalApproximation = Topic::create(array('topic_name' => "Chem 131A - The Orbital Approximation", 'video_url' => 'https://www.youtube.com/watch?start=2540&v=9ZF4gnXv85o', 'video_id' => "9ZF4gnXv85o", 'video_description' => ""));
$HartreeFockApproach = Topic::create(array('topic_name' => "Chem 131A - Hartree-Fock Approach", 'video_url' => 'https://www.youtube.com/watch?start=2982&v=9ZF4gnXv85o', 'video_id' => "9ZF4gnXv85o", 'video_description' => ""));
$HartreeFockApproach = Topic::create(array('topic_name' => "Chem 131A - Hartree-Fock Approach", 'video_url' => 'https://www.youtube.com/watch?start=86&v=xw5cpFLnOhI', 'video_id' => "xw5cpFLnOhI", 'video_description' => ""));
$Correlation = Topic::create(array('topic_name' => "Chem 131A - Correlation", 'video_url' => 'https://www.youtube.com/watch?start=1138&v=xw5cpFLnOhI', 'video_id' => "xw5cpFLnOhI", 'video_description' => ""));
$TakingSpinIntoAccount = Topic::create(array('topic_name' => "Chem 131A - Taking Spin Into Account", 'video_url' => 'https://www.youtube.com/watch?start=1587&v=xw5cpFLnOhI', 'video_id' => "xw5cpFLnOhI", 'video_description' => ""));
$TheSlaterDeterminant = Topic::create(array('topic_name' => "Chem 131A - The Slater Determinant", 'video_url' => 'https://www.youtube.com/watch?start=2399&v=xw5cpFLnOhI', 'video_id' => "xw5cpFLnOhI", 'video_description' => ""));
$ClosedShellAtoms = Topic::create(array('topic_name' => "Chem 131A - Closed Shell Atoms", 'video_url' => 'https://www.youtube.com/watch?start=82&v=UM27jaLv8EU', 'video_id' => "UM27jaLv8EU", 'video_description' => ""));
$TheEnergyofanAtom = Topic::create(array('topic_name' => "Chem 131A - The Energy of an Atom", 'video_url' => 'https://www.youtube.com/watch?start=312&v=UM27jaLv8EU', 'video_id' => "UM27jaLv8EU", 'video_description' => ""));
$FocksContribution = Topic::create(array('topic_name' => "Chem 131A - Fock's Contribution", 'video_url' => 'https://www.youtube.com/watch?start=527&v=UM27jaLv8EU', 'video_id' => "UM27jaLv8EU", 'video_description' => ""));
$OptimizedOrbitalsareOnline = Topic::create(array('topic_name' => "Chem 131A - Optimized Orbitals are Online", 'video_url' => 'https://www.youtube.com/watch?start=820&v=UM27jaLv8EU', 'video_id' => "UM27jaLv8EU", 'video_description' => ""));
$TheMostStableAtom = Topic::create(array('topic_name' => "Chem 131A - The Most Stable Atom", 'video_url' => 'https://www.youtube.com/watch?start=1337&v=UM27jaLv8EU', 'video_id' => "UM27jaLv8EU", 'video_description' => ""));
$HundsRules = Topic::create(array('topic_name' => "Chem 131A - Hund's Rules", 'video_url' => 'https://www.youtube.com/watch?start=1485&v=UM27jaLv8EU', 'video_id' => "UM27jaLv8EU", 'video_description' => ""));
$PredictingStability = Topic::create(array('topic_name' => "Chem 131A - Predicting Stability", 'video_url' => 'https://www.youtube.com/watch?start=2168&v=UM27jaLv8EU', 'video_id' => "UM27jaLv8EU", 'video_description' => ""));
$TheAufbauPrinciple = Topic::create(array('topic_name' => "Chem 131A - The Aufbau Principle", 'video_url' => 'https://www.youtube.com/watch?start=2342&v=UM27jaLv8EU', 'video_id' => "UM27jaLv8EU", 'video_description' => ""));
$ThePeriodicTable = Topic::create(array('topic_name' => "Chem 131A - The Periodic Table", 'video_url' => 'https://www.youtube.com/watch?start=2609&v=UM27jaLv8EU', 'video_id' => "UM27jaLv8EU", 'video_description' => ""));
$Fission = Topic::create(array('topic_name' => "Chem 131A - Fission!", 'video_url' => 'https://www.youtube.com/watch?start=2897&v=UM27jaLv8EU', 'video_id' => "UM27jaLv8EU", 'video_description' => ""));
$ChemicalBonds = Topic::create(array('topic_name' => "Chem 131A - Chemical Bonds", 'video_url' => 'https://www.youtube.com/watch?start=3009&v=UM27jaLv8EU', 'video_id' => "UM27jaLv8EU", 'video_description' => ""));
$TheBornOppenheimerApproximation = Topic::create(array('topic_name' => "Chem 131A - The Born-Oppenheimer Approximation", 'video_url' => 'https://www.youtube.com/watch?start=63&v=JElNVh2vmHA', 'video_id' => "JElNVh2vmHA", 'video_description' => ""));
$TheElectronicHamiltonian = Topic::create(array('topic_name' => "Chem 131A - The Electronic Hamiltonian", 'video_url' => 'https://www.youtube.com/watch?start=592&v=JElNVh2vmHA', 'video_id' => "JElNVh2vmHA", 'video_description' => ""));
$PotentialSurfaces = Topic::create(array('topic_name' => "Chem 131A - Potential Surfaces", 'video_url' => 'https://www.youtube.com/watch?start=666&v=JElNVh2vmHA', 'video_id' => "JElNVh2vmHA", 'video_description' => ""));
$H2 = Topic::create(array('topic_name' => "Chem 131A - H2+", 'video_url' => 'https://www.youtube.com/watch?start=763&v=JElNVh2vmHA', 'video_id' => "JElNVh2vmHA", 'video_description' => ""));
$VariationalApproachForH2 = Topic::create(array('topic_name' => "Chem 131A - Variational Approach For H2+", 'video_url' => 'https://www.youtube.com/watch?start=1363&v=JElNVh2vmHA', 'video_id' => "JElNVh2vmHA", 'video_description' => ""));
$BacktoH2 = Topic::create(array('topic_name' => "Chem 131A - Back to H2+", 'video_url' => 'https://www.youtube.com/watch?start=2464&v=JElNVh2vmHA', 'video_id' => "JElNVh2vmHA", 'video_description' => ""));
$LCAOMOApproximation = Topic::create(array('topic_name' => "Chem 131A - LCAO-MO Approximation", 'video_url' => 'https://www.youtube.com/watch?start=66&v=3Rf8Cbwol7w', 'video_id' => "3Rf8Cbwol7w", 'video_description' => ""));
$VariationalEnergies = Topic::create(array('topic_name' => "Chem 131A - Variational Energies", 'video_url' => 'https://www.youtube.com/watch?start=202&v=3Rf8Cbwol7w', 'video_id' => "3Rf8Cbwol7w", 'video_description' => ""));
$MatrixElements = Topic::create(array('topic_name' => "Chem 131A - Matrix Elements", 'video_url' => 'https://www.youtube.com/watch?start=289&v=3Rf8Cbwol7w', 'video_id' => "3Rf8Cbwol7w", 'video_description' => ""));
$TheOverlapIntegral = Topic::create(array('topic_name' => "Chem 131A - The Overlap Integral", 'video_url' => 'https://www.youtube.com/watch?start=884&v=3Rf8Cbwol7w', 'video_id' => "3Rf8Cbwol7w", 'video_description' => ""));
$TheHabMatrixElement = Topic::create(array('topic_name' => "Chem 131A - The Hab Matrix Element", 'video_url' => 'https://www.youtube.com/watch?start=1541&v=3Rf8Cbwol7w', 'video_id' => "3Rf8Cbwol7w", 'video_description' => ""));
$IsH2Stable = Topic::create(array('topic_name' => "Chem 131A - Is H2+ Stable?", 'video_url' => 'https://www.youtube.com/watch?start=2030&v=3Rf8Cbwol7w', 'video_id' => "3Rf8Cbwol7w", 'video_description' => ""));
$ComparingtheResults = Topic::create(array('topic_name' => "Chem 131A - Comparing the Results", 'video_url' => 'https://www.youtube.com/watch?start=71&v=kzOGmpWiMUI', 'video_id' => "kzOGmpWiMUI", 'video_description' => ""));
$H2MolecularOrbitals = Topic::create(array('topic_name' => "Chem 131A - H2+ Molecular Orbitals", 'video_url' => 'https://www.youtube.com/watch?start=244&v=kzOGmpWiMUI', 'video_id' => "kzOGmpWiMUI", 'video_description' => ""));
$TheCoefficients = Topic::create(array('topic_name' => "Chem 131A - The Coefficients", 'video_url' => 'https://www.youtube.com/watch?start=332&v=kzOGmpWiMUI', 'video_id' => "kzOGmpWiMUI", 'video_description' => ""));
$Normalization = Topic::create(array('topic_name' => "Chem 131A - Normalization", 'video_url' => 'https://www.youtube.com/watch?start=418&v=kzOGmpWiMUI', 'video_id' => "kzOGmpWiMUI", 'video_description' => ""));
$TheOrbitalsAreDifferent = Topic::create(array('topic_name' => "Chem 131A - The Orbitals Are Different", 'video_url' => 'https://www.youtube.com/watch?start=540&v=kzOGmpWiMUI', 'video_id' => "kzOGmpWiMUI", 'video_description' => ""));
$TheVirialTheorem = Topic::create(array('topic_name' => "Chem 131A - The Virial Theorem", 'video_url' => 'https://www.youtube.com/watch?start=862&v=kzOGmpWiMUI', 'video_id' => "kzOGmpWiMUI", 'video_description' => ""));
$CheckingOurMO = Topic::create(array('topic_name' => "Chem 131A - Checking Our MO", 'video_url' => 'https://www.youtube.com/watch?start=1707&v=kzOGmpWiMUI', 'video_id' => "kzOGmpWiMUI", 'video_description' => ""));
$OptimizingtheEnergy = Topic::create(array('topic_name' => "Chem 131A - Optimizing the Energy", 'video_url' => 'https://www.youtube.com/watch?start=2221&v=kzOGmpWiMUI', 'video_id' => "kzOGmpWiMUI", 'video_description' => ""));
$Polarization = Topic::create(array('topic_name' => "Chem 131A - Polarization", 'video_url' => 'https://www.youtube.com/watch?start=208&v=8mFT5s6kQAQ', 'video_id' => "8mFT5s6kQAQ", 'video_description' => ""));
$H2 = Topic::create(array('topic_name' => "Chem 131A - H2", 'video_url' => 'https://www.youtube.com/watch?start=753&v=8mFT5s6kQAQ', 'video_id' => "8mFT5s6kQAQ", 'video_description' => ""));
$MolecularOrbitalsforH2 = Topic::create(array('topic_name' => "Chem 131A - Molecular Orbitals for H2", 'video_url' => 'https://www.youtube.com/watch?start=950&v=8mFT5s6kQAQ', 'video_id' => "8mFT5s6kQAQ", 'video_description' => ""));
$ThePotentialEnergyCurve = Topic::create(array('topic_name' => "Chem 131A - The Potential Energy Curve", 'video_url' => 'https://www.youtube.com/watch?start=1104&v=8mFT5s6kQAQ', 'video_id' => "8mFT5s6kQAQ", 'video_description' => ""));
$TheLCAOMOProblem = Topic::create(array('topic_name' => "Chem 131A - The LCAO-MO Problem", 'video_url' => 'https://www.youtube.com/watch?start=1219&v=8mFT5s6kQAQ', 'video_id' => "8mFT5s6kQAQ", 'video_description' => ""));
$TheValenceBondApproach = Topic::create(array('topic_name' => "Chem 131A - The Valence Bond Approach", 'video_url' => 'https://www.youtube.com/watch?start=1910&v=8mFT5s6kQAQ', 'video_id' => "8mFT5s6kQAQ", 'video_description' => ""));
$WrappingUpH2 = Topic::create(array('topic_name' => "Chem 131A - Wrapping Up H2", 'video_url' => 'https://www.youtube.com/watch?start=2428&v=8mFT5s6kQAQ', 'video_id' => "8mFT5s6kQAQ", 'video_description' => ""));
$BondOrder = Topic::create(array('topic_name' => "Chem 131A - Bond Order", 'video_url' => 'https://www.youtube.com/watch?start=2753&v=8mFT5s6kQAQ', 'video_id' => "8mFT5s6kQAQ", 'video_description' => ""));
$ComparingH2ThroughHe2 = Topic::create(array('topic_name' => "Chem 131A - Comparing H2+ Through He2", 'video_url' => 'https://www.youtube.com/watch?start=2848&v=8mFT5s6kQAQ', 'video_id' => "8mFT5s6kQAQ", 'video_description' => ""));
$MODiagrams = Topic::create(array('topic_name' => "Chem 131A - MO Diagrams", 'video_url' => 'https://www.youtube.com/watch?start=29&v=d96FDewT4mQ', 'video_id' => "d96FDewT4mQ", 'video_description' => ""));
$QualitativeGuidelines = Topic::create(array('topic_name' => "Chem 131A - Qualitative Guidelines", 'video_url' => 'https://www.youtube.com/watch?start=216&v=d96FDewT4mQ', 'video_id' => "d96FDewT4mQ", 'video_description' => ""));
$HomonuclearDiatomics = Topic::create(array('topic_name' => "Chem 131A - Homonuclear Diatomics", 'video_url' => 'https://www.youtube.com/watch?start=608&v=d96FDewT4mQ', 'video_id' => "d96FDewT4mQ", 'video_description' => ""));
$BondOrderMatchesIntuition = Topic::create(array('topic_name' => "Chem 131A - Bond Order Matches Intuition", 'video_url' => 'https://www.youtube.com/watch?start=1093&v=d96FDewT4mQ', 'video_id' => "d96FDewT4mQ", 'video_description' => ""));
$PhotoelectronSpectroscopy = Topic::create(array('topic_name' => "Chem 131A - Photoelectron Spectroscopy", 'video_url' => 'https://www.youtube.com/watch?start=1782&v=d96FDewT4mQ', 'video_id' => "d96FDewT4mQ", 'video_description' => ""));
$HybridOrbitals = Topic::create(array('topic_name' => "Chem 131A - Hybrid Orbitals", 'video_url' => 'https://www.youtube.com/watch?start=2153&v=d96FDewT4mQ', 'video_id' => "d96FDewT4mQ", 'video_description' => ""));
$MakingBonds = Topic::create(array('topic_name' => "Chem 131A - Making Bonds", 'video_url' => 'https://www.youtube.com/watch?start=2713&v=d96FDewT4mQ', 'video_id' => "d96FDewT4mQ", 'video_description' => ""));
$NormalizingtheHybrids = Topic::create(array('topic_name' => "Chem 131A - Normalizing the Hybrids", 'video_url' => 'https://www.youtube.com/watch?start=2904&v=d96FDewT4mQ', 'video_id' => "d96FDewT4mQ", 'video_description' => ""));
$OtherHybridCombinations = Topic::create(array('topic_name' => "Chem 131A - Other Hybrid Combinations", 'video_url' => 'https://www.youtube.com/watch?start=3009&v=d96FDewT4mQ', 'video_id' => "d96FDewT4mQ", 'video_description' => ""));
$MOPictureforCH4 = Topic::create(array('topic_name' => "Chem 131A - MO Picture for CH4", 'video_url' => 'https://www.youtube.com/watch?start=98&v=O3Jx5Y38aKs', 'video_id' => "O3Jx5Y38aKs", 'video_description' => ""));
$CH4PES = Topic::create(array('topic_name' => "Chem 131A - CH4 PES", 'video_url' => 'https://www.youtube.com/watch?start=833&v=O3Jx5Y38aKs', 'video_id' => "O3Jx5Y38aKs", 'video_description' => ""));
$Delocalization = Topic::create(array('topic_name' => "Chem 131A - Delocalization", 'video_url' => 'https://www.youtube.com/watch?start=1132&v=O3Jx5Y38aKs', 'video_id' => "O3Jx5Y38aKs", 'video_description' => ""));
$Ethylene = Topic::create(array('topic_name' => "Chem 131A - Ethylene", 'video_url' => 'https://www.youtube.com/watch?start=1305&v=O3Jx5Y38aKs', 'video_id' => "O3Jx5Y38aKs", 'video_description' => ""));
$Benzene = Topic::create(array('topic_name' => "Chem 131A - Benzene", 'video_url' => 'https://www.youtube.com/watch?start=2042&v=O3Jx5Y38aKs', 'video_id' => "O3Jx5Y38aKs", 'video_description' => ""));
$Aromaticity = Topic::create(array('topic_name' => "Chem 131A - Aromaticity", 'video_url' => 'https://www.youtube.com/watch?start=2624&v=O3Jx5Y38aKs', 'video_id' => "O3Jx5Y38aKs", 'video_description' => ""));
$MatterandRadiation = Topic::create(array('topic_name' => "Chem 131A - Matter and Radiation", 'video_url' => 'https://www.youtube.com/watch?start=311&v=n8si8iJgt6Y', 'video_id' => "n8si8iJgt6Y", 'video_description' => ""));
$PostulatesofQuantumMechanics = Topic::create(array('topic_name' => "Chem 131A - Postulates of Quantum Mechanics", 'video_url' => 'https://www.youtube.com/watch?start=453&v=n8si8iJgt6Y', 'video_id' => "n8si8iJgt6Y", 'video_description' => ""));
$Measurement = Topic::create(array('topic_name' => "Chem 131A - Measurement", 'video_url' => 'https://www.youtube.com/watch?start=611&v=n8si8iJgt6Y', 'video_id' => "n8si8iJgt6Y", 'video_description' => ""));
$Uncertainty = Topic::create(array('topic_name' => "Chem 131A - Uncertainty", 'video_url' => 'https://www.youtube.com/watch?start=731&v=n8si8iJgt6Y', 'video_id' => "n8si8iJgt6Y", 'video_description' => ""));
$TimeEvolution = Topic::create(array('topic_name' => "Chem 131A - Time Evolution", 'video_url' => 'https://www.youtube.com/watch?start=816&v=n8si8iJgt6Y', 'video_id' => "n8si8iJgt6Y", 'video_description' => ""));
$BoundStates = Topic::create(array('topic_name' => "Chem 131A - Bound States", 'video_url' => 'https://www.youtube.com/watch?start=937&v=n8si8iJgt6Y', 'video_id' => "n8si8iJgt6Y", 'video_description' => ""));
$Tunneling = Topic::create(array('topic_name' => "Chem 131A - Tunneling", 'video_url' => 'https://www.youtube.com/watch?start=1076&v=n8si8iJgt6Y', 'video_id' => "n8si8iJgt6Y", 'video_description' => ""));
$UnboundStates = Topic::create(array('topic_name' => "Chem 131A - Unbound States", 'video_url' => 'https://www.youtube.com/watch?start=1189&v=n8si8iJgt6Y', 'video_id' => "n8si8iJgt6Y", 'video_description' => ""));
$ApproximateSolutions = Topic::create(array('topic_name' => "Chem 131A - Approximate Solutions", 'video_url' => 'https://www.youtube.com/watch?start=1266&v=n8si8iJgt6Y', 'video_id' => "n8si8iJgt6Y", 'video_description' => ""));
$Spectroscopy = Topic::create(array('topic_name' => "Chem 131A - Spectroscopy", 'video_url' => 'https://www.youtube.com/watch?start=1468&v=n8si8iJgt6Y', 'video_id' => "n8si8iJgt6Y", 'video_description' => ""));
$AtomicStructure = Topic::create(array('topic_name' => "Chem 131A - Atomic Structure", 'video_url' => 'https://www.youtube.com/watch?start=1579&v=n8si8iJgt6Y', 'video_id' => "n8si8iJgt6Y", 'video_description' => ""));
$PauliPrinciple = Topic::create(array('topic_name' => "Chem 131A - Pauli Principle", 'video_url' => 'https://www.youtube.com/watch?start=1985&v=n8si8iJgt6Y', 'video_id' => "n8si8iJgt6Y", 'video_description' => ""));
$Molecules = Topic::create(array('topic_name' => "Chem 131A - Molecules", 'video_url' => 'https://www.youtube.com/watch?start=2051&v=n8si8iJgt6Y', 'video_id' => "n8si8iJgt6Y", 'video_description' => ""));
$ChemicalBonds = Topic::create(array('topic_name' => "Chem 131A - Chemical Bonds", 'video_url' => 'https://www.youtube.com/watch?start=2545&v=n8si8iJgt6Y', 'video_id' => "n8si8iJgt6Y", 'video_description' => ""));
$Dissociation = Topic::create(array('topic_name' => "Chem 131A - Dissociation", 'video_url' => 'https://www.youtube.com/watch?start=2597&v=n8si8iJgt6Y', 'video_id' => "n8si8iJgt6Y", 'video_description' => ""));
$DelocalizedSystems = Topic::create(array('topic_name' => "Chem 131A - Delocalized Systems", 'video_url' => 'https://www.youtube.com/watch?start=2704&v=n8si8iJgt6Y', 'video_id' => "n8si8iJgt6Y", 'video_description' => ""));

    }
}
