<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateBbbsessionTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('bbbsessions', function (Blueprint $table) {
            $table->increments('id');

            $table->string('meeting_name');
            $table->string('meeting_id'); // uniquely generated by BBB
            $table->string('modpw');
            $table->string('attendeepw');

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('bbbsessions');
    }
}
